### ISSUE TITLE
Provide an arm64 version on PyPI

### ISSUE THREAD

**Issue by jbeyerstedt** [mavlink/MAVSDK-Python#117]
Currently there are just versions of the mavsdk package in PyPI for linux, windows and macOS using the x86_64/ amd64 architecture. Is it possible to also provide a linux version for arm64 and armhf (older raspberry pi).

And maybe you should add to the pip readme section, what operating systems and processor architectures are supported, so you don't have to dig through the pip verbose output to find, what the issue really is.

Thanks

**Comment by julianoes** [comment]
This would indeed be nice.

The instructions to build for arm64 would be something along the lines of:

```
docker run --rm dockcross/linux-arm64 > ./dockcross-linux-arm64
./dockcross-linux-arm64 cmake -Bbuild -S. -DBUILD_BACKEND=ON
./dockcross-linux-arm64 cmake --build build
```

And then we just need to figure out how to get the artefacts released and into PyPi.

**Comment by JonasVautherin** [comment]
Is there an equivalent to `manylinux-x86_64` on arm? At least I found [some discussions](https://github.com/pypa/manylinux/issues/84) about it... Not sure :thinking:.

Also I'm curious about whether we could have `pip` build `mavsdk_server` from sources, but I've never done that so I don't know if we can tell pip to `git clone` and then run `cmake` and `cmake --build`. Ideas?

**Comment by hrw** [comment]
@JonasVautherin manylinux2014 will solve that problem. WIP.

**Comment by julianoes** [comment]
@hrw thanks for the note.
https://www.python.org/dev/peps/pep-0599/

**Comment by hrw** [comment]
manylinux2014 is published already. Any plans to use it?

**Comment by JonasVautherin** [comment]
Yes, through dockcross. I started looking into that last week, hopefully I can spend some more time on it soon!

**Comment by JonasVautherin** [comment]
@hrw: working on it, I got `dockcross-manylinux2014-x64` to work on my machine (was pretty easy actually). Next is aarch64! See https://github.com/dockcross/dockcross/issues/358!

BTW, do you know if there is a plan in supporting 32 bits arm architectures as well (e.g. armv7)?

**Comment by hrw** [comment]
PEP599 lists armv7l but I do not track how it goes.

**Comment by hrw** [comment]
Travis CI does not support 32bit arm could be one of reasons.

**Comment by JonasVautherin** [comment]
I think it should not be that. The point of the docker image is to cross-compile, so it doesn't have to run on an arm system... Good to know about PEP599, thanks for the information :-)

**Comment by hrw** [comment]
Maybe for you it is to cross-compile. I use them natively. Either on available machines or on CI systems.

**Comment by JonasVautherin** [comment]
Oh, I see. Thanks for the explanation :blush:. Well, we'll see if that happens at some point. Right now I have issues running the aarch64 docker image :confused:. But at least the x64 seems to be working!

**Comment by hrw** [comment]
Any update @JonasVautherin?

**Comment by JonasVautherin** [comment]
I haven't had time to move forward on that, but I did some research on how to do it in dockcross. I hope I'll find some time to continue it soon!

**Comment by JonasVautherin** [comment]
We now provide it on pypi: https://files.pythonhosted.org/packages/46/24/8a71b6147111d4819750e453321430d93d8b3ba5bacd79dd68f618f6df3d/mavsdk-0.15.0-py3-none-manylinux2014_aarch64.whl

**Comment by SasoPavlic** [comment]
We tested a new wheel on [Navq ](https://nxp.gitbook.io/8mmnavq/) companion computer (aarch64v8) and is still installing forever (stops on grpcio package).
Command used: `pip install wheel_file.whl`

**Comment by julianoes** [comment]
@SasoPavlic I assume that's a grpcio problem. See https://github.com/grpc/grpc/issues/21283.

**Comment by nihanaltaytass** [comment]
I have pixhawk4 with px4 software and I would like to send MAVLINK signals to my pixhawk from jetson Nano  which has arm64 system. Is it possible or is there any update

**Comment by cryptik** [comment]
@nihanaltaytass, MAVSDK and mavsdk_server work fine on Jetson.  I have it running on a Jetson Xavier and Orin (both aarch64 systems).  You can install both with just a `pip install mavsdk`.  The version I am running is `v1.4.0` on `python 3.8.10`.   The the only thing is you may have to create a symlink from where `mavsdk_server` is installed and the `./local/bin` folder.. or you can put it in your python_path.  But in any case, it works great on linux arm.

**Comment by Pragadesh-45** [comment]
@nihanaltaytass Hi. I'm currently working on the exact setup. Any updates???

If possible: [https://github.com/thien94/vision_to_mavros/blob/master/scripts/d4xx_to_mavlink.py](url) provide me any alternative to this.
