### ISSUE TITLE
MAVSDK-Python 0.3.0 not available on pip for macOS

### ISSUE THREAD

**Issue by alexander-wu-aw** [mavlink/MAVSDK-Python#118]
For some reason, I can't upgrade to mavsdk 0.3.0.

Whenever I try `pip install mavsdk` or `pip install --upgrade mavsdk`, it only gives me version 0.2.0. I've also tried `--force-reinstall`, but it still installs 0.2.0.

When I run `pip install mavsdk==0.3.0` it says:

"RROR: Could not find a version that satisfies the requirement mavsdk==0.3.0 (from versions: 0.1.0, 0.2.0)
ERROR: No matching distribution found for mavsdk==0.3.0" 

Yet, if I run `pip search mavsdk`, it shows the latest version is indeed 0.3.0 and that I have the 0.2.0 version installed.

**Comment by julianoes** [comment]
@JonasVautherin can you check this?

**Comment by JonasVautherin** [comment]
Linux, or macOS?

**Comment by alexander-wu-aw** [comment]
On MacOS

**Comment by JonasVautherin** [comment]
That's because it is not released on macOS yet. I'll do that ASAP and will communicate here and on Slack (#mavsdk)!

**Comment by alexander-wu-aw** [comment]
Thanks a lot!

**Comment by JonasVautherin** [comment]
That's finally released.

To install (first time):

```
pip install mavsdk
```

To upgrade:

```
pip install --upgrade mavsdk
```

It should install mavsdk 0.3.0, as can be seen with the output of `pip show mavsdk`:

```
$ pip show mavsdk
Name: mavsdk
Version: 0.3.0
```
