### ISSUE TITLE
Control Of AUX PWM output on autopilot while in flight over mavlink

### ISSUE THREAD

**Issue by EkpoEsua** [mavlink/MAVSDK-Python#121]
Please I am trying to do some form of automation while in flight, so I want to inquire if I can control the PWM of the AUX output using this SDK while the drone is in flight, if not please what other options are available for me. Thanks.

**Comment by julianoes** [comment]
You could try to use offboard actuator control but it will probably require some debugging and going through PX4 code actually get it working.

https://github.com/mavlink/MAVSDK-Python/blob/1e381fe30193bc878c5deebe15c23395e46d5c8f/mavsdk/generated/offboard.py#L173-L194

**Comment by EkpoEsua** [comment]
wow!, thanks a bunch, I could have never thought it can be done that way, I am gonna check it out right away, I really appreciate. Thanks a million.

Then just one question, does this SDK has an api that supports sending raw MAVLink messages/commands to an autopilot just like DroneKit-Python SDK using [.send_mavlink()](https://dronekit-python.readthedocs.io/en/latest/automodule.html#dronekit.Vehicle.send_mavlink) and [.message_factory()](https://dronekit-python.readthedocs.io/en/latest/automodule.html#dronekit.Vehicle.message_factory) api, I felt I should stick with Dronecode SDK since it is really optimized for PX4 which I am working on.

**Comment by julianoes** [comment]
For a raw MAVLink interface you can use [MAVLink Passthrough](https://mavsdk.mavlink.io/develop/en/api_reference/classmavsdk_1_1_mavlink_passthrough.html) but it's only available using C++ because it depends on the MAVLink generated C headers. It is therefore not something that can be exposed in the wrappers such as MAVSDK-Python.
