### ISSUE TITLE
Does function set_position_ned work well ?

### ISSUE THREAD

**Issue by minimal1** [mavlink/MAVSDK-Python#122]
I tried drone control by Offboard. 
2 functions ( set_velocity_ned, set_velocity_body) worked well, but set_position_ned didn't.

I ran offboard example code using function set_position_ned.
there was no error to give command, but the drone was not moving.
Just stayed on ground like there was no command.

According to https://github.com/mavlink/MAVSDK-docs/blob/develop/en/guide/offboard.md, Position or thrust set points is not supported. 

How is it now ?

**Comment by julianoes** [comment]
It would also be interesting if you could try the C++ integration test:
https://github.com/mavlink/MAVSDK/blob/develop/src/integration_tests/offboard_position.cpp

**Comment by minimal1** [comment]
> @minimal1 what PX4 version were you using, and what MAVSDK version?
 Yes, I am using PX4. If you mean MAVSDK-Python, it is 0.3.0.
 
> It would also be interesting if you could try the C++ integration test:
> https://github.com/mavlink/MAVSDK/blob/develop/src/integration_tests/offboard_position.cpp
I would try this using real drone, right ?

**Comment by julianoes** [comment]
I mean the PX4 version. You can get it using `ver all` in `nsh>` or `pxh>`.

I would try it in SITL first so you know what to expect.

**Comment by julianoes** [comment]
Stale, closing.

**Comment by moshibe** [comment]
@minimal1
Did you find out why it's not working? 
I'm having the same problem and I'm having trouble. 
Please give me some advice.
