### ISSUE TITLE
Odometry unavailable?

### ISSUE THREAD

**Issue by hughleo90** [mavlink/MAVSDK-Python#125]
I installed the mavsdk-python running the command 'pip3 install mavsdk' and none of the methods related to the odometry are present in the 'telemetry.py' file, although they're available in the git. 
Is it possible to update the pip command? Odometry updates would be very useful.

**Comment by julianoes** [comment]
This has been added recently: https://github.com/mavlink/MAVSDK-Proto/pull/107
I expect it will come with the next release.

**Comment by julianoes** [comment]
Please try `pip install --upgrade mavsdk` to get 0.4.0. (On macOS stay patient.)
