### ISSUE TITLE
How to access the ".Shell" plugin from the System (drone) class

### ISSUE THREAD

**Issue by EkpoEsua** [mavlink/MAVSDK-Python#126]
Please I can't seem to have access to the 
` drone.shell `
plugin from the system class,
AttributeError: 'System' object has no attribute 'Shell'
 how do I go about that Thanks.

**Comment by julianoes** [comment]
This will be available in the next release, stay tuned.

**Comment by julianoes** [comment]
Try `pip install --upgrade mavsdk` which should get you 0.4.0 (and macOS should follow soon).
