### ISSUE TITLE
Cannot connect to mavsdk-server

### ISSUE THREAD

**Issue by chris-aeviator** [mavlink/MAVSDK-Python#130]
Hi! I'm struggling to get the internally started or externally started mavsdk server connected. I can therefore not reach any further in every example than `drone = System()`

### System Info
- Arch Linux
- conda env with python=3.7
- `pip3 install mavsdk` (0.4.0)

### Expected Behavior 
When I run `python3 takeof_land.py` I expect to see the SDK connecting and running the example code

### Actual Behavior

`Waiting for mavsdk_server to be ready...`

I checked that the mavsdk binary is inside the conda env site packages folder, I confirm an internal version is started, by starting the binary (from github releases page of mavsdk) after the python script has started and it errors out that the port (50051) is already taken.

To test the connection to the externally started mavsdk binary I invoke the init like so `drone = System(mavsdk_server_address="udp://0.0.0.0", port=50051)`

**EDIT**:

my mavsdk server (externally started) is successfully connecting to my PX4 SITL instance, and I can see chatter in the px4 sitl instance in sync with mavsdk server

**EDIT 2**:

MAVSDK log
```
[09:30:59|Info ] MAVSDK version: 0.21.1 (mavsdk_impl.cpp:25)
[09:30:59|Debug] New: System ID: 0 Comp ID: 0 (mavsdk_impl.cpp:390)
[09:30:59|Info ] Server set to listen on 0.0.0.0:50051 (grpc_server.cpp:47)
[09:30:59|Info ] Server started (grpc_server.cpp:31)
[…]
```

**EDIT 3:**:

since https://github.com/mavlink/MAVSDK-Python/blob/3ba03ca1eccbbc7d0163b170402a6cf54577b039/mavsdk/system.py#L31  mentions the parameter `mavsdk_server_address` actually containing the port as well as the port parameter (?) ("     Port of the running mavsdk_server instance specified by mavsdk_server_address.") I have also tried setting `mavsdk_server_address="udp://0.0.0.0:50051"` with no different result

**Comment by JonasVautherin** [comment]
> drone = System(mavsdk_server_address="udp://0.0.0.0", port=50051)

I think that's wrong. Can you do `drone = System(mavsdk_server_address="127.0.0.1")` instead? That should connect you to the externally-started instance.

For the "internally-started" instance, could you try to find the binary (somewhere in the installation, probably ending in `mavsdk/bin/mavsdk_server`) and try to start that manually?

**Comment by chris-aeviator** [comment]
I can confirm being able to connect everything successfully with 

```python
drone = System(mavsdk_server_address="127.0.0.1")
await drone.connect(system_address="udp://:14540)
```

*with Airsim & PX4 sitl

**Comment by 21shrinit** [comment]
> > drone = System(mavsdk_server_address="udp://0.0.0.0", port=50051)
> 
> I think that's wrong. Can you do `drone = System(mavsdk_server_address="127.0.0.1")` instead? That should connect you to the externally-started instance.
> 
> For the "internally-started" instance, could you try to find the binary (somewhere in the installation, probably ending in `mavsdk/bin/mavsdk_server`) and try to start that manually?



I tried to find but in bin the mavsdk_server is not there
and I am getting the which says to start server manually but I'm not getting resource for starting the server manually

**Comment by julianoes** [comment]
@21shrinit please don't necrobump and create a new issue and provide the information about the steps you tried, etc.
