### ISSUE TITLE
download_mission() not working

### ISSUE THREAD

**Issue by petergerten** [mavlink/MAVSDK-Python#138]
This is reproducible in `MAVSDK/develop/docker/Dockerfile-Ubuntu-18.04-PX4-SITL` docker container:

When adding this download mission command:

`await drone.mission.download_mission()`

to the mission.py example, I get the following error:
```
  File "test.py", line 57, in run
    await drone.mission.download_mission()
  File "/usr/local/lib/python3.6/dist-packages/mavsdk/generated/mission.py", line 634, in download_mission
    return [MissionItem].translate_from_rpc(response.mission_items)
AttributeError: 'list' object has no attribute 'translate_from_rpc'
```

**Comment by JonasVautherin** [comment]
Seems like a bug in the autogenerated code. I'll have a look ASAP.
