### ISSUE TITLE
is start_mavlink() call still up to date?

### ISSUE THREAD

**Issue by gulyvz** [mavlink/MAVSDK-Python#145]
Hi,
I just started using Mavsdk. ReadMe file says I need to call start_mavlink(). There is no such file in Mavsdk. Is start_mavlink() still up to date? I think the ReadMe file should be updated.

**Comment by JonasVautherin** [comment]
You're right, it is outdated. The way to connect is as shown in the examples (e.g. [here](https://github.com/mavlink/MAVSDK-Python/blob/master/examples/takeoff_and_land.py#L9-L10)):

```python
drone = System()
await drone.connect(system_address="udp://:14540")
```
