### ISSUE TITLE
Stuck at  "Waiting for Drone to connect" while trying to connect drone over serial to run example takeoff-and-land.py

### ISSUE THREAD

**Issue by yash2410** [mavlink/MAVSDK-Python#159]
`   drone = System()
    await drone.connect(system_address="serial:///dev/ttyACM0:57600")
    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():`

The output is stuck on 
`Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...
`
I checked mavlink status on QGC and gave me this output
![insatnce #0 serial](https://user-images.githubusercontent.com/28266446/74901288-6ae24600-53c8-11ea-93ac-f0cffa529074.png)
![instance serial 1](https://user-images.githubusercontent.com/28266446/74901359-a41ab600-53c8-11ea-95c0-019b52f9d0ab.png)

I changed the baudrate match to QGC but it didn't make an difference.
I am running Ubuntu 18.04

**Comment by julianoes** [comment]
When you try this, is QGC shutdown so it is not blocking the serial port?

**Comment by yash2410** [comment]
It was shutdown. I opened QGC just to check the mavlink status

**Comment by julianoes** [comment]
What platform is this on? Can you try to run `mavsdk_server` manually to check if it is connecting?

**Comment by yash2410** [comment]
This is on Ubuntu 18.04 running python3.6 and mavsdk version 0.6.1. The drone was serially connected through USB.
I have solved it now by going for a UDP connection instead.

**Comment by rachoun** [comment]
Hello, can you please tell me what could be the max tx and rx rates?

**Comment by JonasVautherin** [comment]
@rachoun Hello! This is off-topic here. Please open a new issue to ask your question :blush:
