### ISSUE TITLE
MAVLink Passthrough

### ISSUE THREAD

**Issue by coderkalyan** [mavlink/MAVSDK-Python#161]
Is there anything we can do to make MAVLink passthrough available in the Python interface? Would it be possible to connect it to pymavlink? I'm aware that the current C++ interface connects to C bindings directly, and this won't be easy - but is there anything we can do?

**Comment by julianoes** [comment]
Also see: https://github.com/mavlink/MAVSDK-Python/issues/121#issuecomment-546364100

It could be made using runtime string lookup for the message definitions but I don't believe that makes a lot of sense. At this point you could just use a MAVLink implementation in Python.

What's your specific use case?
