### ISSUE TITLE
Switch between offboard and mission modes

### ISSUE THREAD

**Issue by deepak-1530** [mavlink/MAVSDK-Python#166]
I am able to switch from mission mode to offboard but cannot go back to mission mode. Is there a way to do it?

**Comment by JonasVautherin** [comment]
What happens when you stop the offboard mode? Isn't it supposed to go back to `hold`?

**Comment by deepak-1530** [comment]
Yes it goes back to hold. It stays in hold. How do i continue the mission from there?

**Comment by julianoes** [comment]
You should be able to use `continue` from `mission`.

**Comment by deepak-1530** [comment]
I did not find continue in mission. I found pause_mission function but not continue

**Comment by julianoes** [comment]
Sorry, start mission should do it too.

**Comment by deepak-1530** [comment]
start_mission() works fine. Thanks
