### ISSUE TITLE
How to connect serial in Windows?

### ISSUE THREAD

**Issue by LiangR2017** [mavlink/MAVSDK-Python#167]
Hope u still fine.and of course hello to u.
Find your codes
Serial: 

> serial:///path/to/serial/dev[:baudrate]

but it seems to work on linux only
Have tried   `awaitdrone.connect(system_address="serial://com14:115200")` but didn't work. 
Can u help me?thanks

**Comment by LiangR2017** [comment]
also tried 

> await drone.connect(system_address="serial:com14:115200")

doesnt work .

**Comment by LiangR2017** [comment]
trying to install unbuntu now .still want to know how to connect in windows
tell me if anybody knows.thanks a lot!

**Comment by julianoes** [comment]
@LiangR2017 what error do you get when you try that?

Can you try `serial://COM14:115200`

**Comment by LiangR2017** [comment]
@julianoes just show these and i also tried " serial://COM14:115200"
> Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...

**Comment by maxwelllwang** [comment]
what are the parameters to connect with mavsdk_server manually? when you run ./mavsdk_server i know you can specify port as -p 50051. how do you specify connection address?

**Comment by maxwelllwang** [comment]
Ok I successfully connected on ubuntu with ./mavsdk_server -p 50051 serial///dev/ttyACM0:57600 
but its telling me im sending invalid commands

**Comment by JonasVautherin** [comment]
I'm assuming you meant `./mavsdk_server -p 50051 serial:///dev/ttyACM0:57600` (note the `:`).

> its telling me im sending invalid commands

What are you sending, and what does it say precisely? :sweat_smile:

**Comment by maxwelllwang** [comment]
I think you addressed it in the other thread because my pixhawk is running ardupilot not pixhawk
Oops forgot the `:`
