### ISSUE TITLE
Velocity data from telemetry?

### ISSUE THREAD

**Issue by deepak-1530** [mavlink/MAVSDK-Python#169]
How can I get the current drone velocity in body and NED frame?

**Comment by breathedigital** [comment]
Is this what you're looking for?

https://mavsdk.mavlink.io/develop/en/api_reference/structmavsdk_1_1_telemetry_1_1_angular_velocity_n_e_d.html

**Comment by deepak-1530** [comment]
This gives angular velocity. I need linear velocity of the drone in either Body or NED frame.

**Comment by breathedigital** [comment]
https://mavsdk.mavlink.io/develop/en/api_reference/structmavsdk_1_1_telemetry_1_1_velocity_n_e_d.html

**Comment by deepak-1530** [comment]
It's sorted now. This is how the velocity data can be accessed in NED frame.

async def print_velocity(drone):
    async for speed_NED in drone.telemetry.ground_speed_ned():
        print(speed_NED)

**Comment by deepak-1530** [comment]
-
