### ISSUE TITLE
MAVLink version

### ISSUE THREAD

**Issue by Safranek42** [mavlink/MAVSDK-Python#184]
Hi,

This might be an obvious question but I couldn't find it anywhere.
Does MAVSDK(-Python) uses mavlink 1 or mavlink 2 dialect/version? I saw in pymavlink it can be chosen which one to generate, but using MAVSDK-Python I haven't found anything regarding this.

Thanks in advance!

**Comment by JonasVautherin** [comment]
I would say MAVLink 2: see https://github.com/mavlink/MAVSDK/tree/develop/src/third_party/mavlink/include/mavlink
