### ISSUE TITLE
mavsdk 0.7.0 with PX4 1.11.0 - Mission Errors

### ISSUE THREAD

**Issue by breathedigital** [mavlink/MAVSDK-Python#190]
Hello -
Upgraded PX4 FW & MavSDK-Python to 1.11.0 80 & 0.7.0.

And, now we're experiencing a classic syndrome _it works on my computer, but not elsewhere! 🤷‍♂️_

Code Fragment:
````
async def uploadMission(missionPlanArray):
    try:
        print("-- Uploading mission")
        missionPlan = MissionPlan(missionPlanArray)
        print(missionPlan)
        print(missionPlan.mission_items[0])
        print(mavServer)
        await mavServer.mission.set_return_to_launch_after_mission(True)
        await mavServer.mission.upload_mission(missionPlan)
        return True
    except Exception as e:
        print(e)
        return False
````

Output:
````
-- Uploading mission

MissionPlan: [mission_items: [<mavsdk.generated.mission.MissionItem object at 0x7f00889e6850>, <mavsdk.generated.mission.MissionItem object at 0x7f008643c1d0>, <mavsdk.generated.mission.MissionItem object at 0x7f008643c310>]]

MissionItem: [latitude_deg: 47.3976087023, longitude_deg: 8.5452572643, relative_altitude_m: 2, speed_m_s: 10, is_fly_through: True, gimbal_pitch_deg: nan, gimbal_yaw_deg: nan, camera_action: NONE, loiter_time_s: nan, camera_photo_interval_s: nan]

<mavsdk.system.System object at 0x7f008aedf750>

UNKNOWN: ''; origin: set_return_to_launch_after_mission(); params: (True,)
````

Interestingly, when I comment this line

````
# await mavServer.mission.set_return_to_launch_after_mission(True)
````
my mission got uploaded successfully. However, it denies arming with the following error : 
````
COMMAND_DENIED: 'Command denied'; origin: arm(); params: ()
````

And, PX4 SITL logs show this:
````
WARN  [navigator] First waypoint too far away: 5335133 meters, 900 max.
WARN  [navigator] mission check failed
````
  
**How to reproduce:**

Run `mission.py` from `MAVSDK-Python/examples` directory on python 3.7

The error message is quite vague -- its going through UNKNOWN MISSION ERROR path with no significant message. Any help is highly appreciated!

Cheers!
ram

**Comment by JonasVautherin** [comment]
> Upgraded PX4 FW & MavSDK-Python to 1.11.0 80 & 0.7.0.

Are you running `mavsdk_server` manually, or are you using the embedded one (if you don't know, then it means that you use the embedded one, which is started automatically :laughing:).

If you run `mavsdk_server` manually, which version are you using? MAVSDK-Python 0.7.0 [requires `mavsdk_server` v0.26.0](https://github.com/mavlink/MAVSDK-Python/blob/0.7.0/MAVSDK_SERVER_VERSION).

**Comment by breathedigital** [comment]
Appreciate your quick reaction! 

mavsdk_server was run manually @ -p 50051. 
Indeed, it was older than 0.26.0 causing this error.

Many Thanks! 🎇

_ps: A compatibility matrix of **mavsdk_server**, **mavsdk-python**, **px4 firmware** would ease things drastically._
