### ISSUE TITLE
I faced this error every time when i go to install numpy

### ISSUE THREAD

**Issue by Arkajit7** [mavlink/MAVSDK-Python#192]
![IMG20200524004014](https://user-images.githubusercontent.com/44799885/82738887-b6561880-9d58-11ea-8fd6-fc58089b12aa.jpg)

**Comment by julianoes** [comment]
Numpy has nothing to do with MAVSDK. What are you trying to do?

The error that I see is "NewConnectionError" which would hint something with your conenction is not working properly.

**Comment by julianoes** [comment]
There was no follow up, closing.
