### ISSUE TITLE
Fix PyPi description

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK-Python#210]
I think at some point I broke the description on PyPi.

https://pypi.org/project/mavsdk/

**Comment by JonasVautherin** [comment]
What is broken there? I see the description, at least :thinking:

**Comment by julianoes** [comment]
Huh! It's fixed itself. With 0.9.0 it was broken: https://pypi.org/project/mavsdk/0.9.0/

**Comment by JonasVautherin** [comment]
Good, I don't wanna know :D
