### ISSUE TITLE
API Reference documentation seems to be broken

### ISSUE THREAD

**Issue by jank324** [mavlink/MAVSDK-Python#211]
The [API Reference documentation](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com) only shows content on the first page. Any of the pages only show the title, but no further content.

[Example](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/mission.html)
<img width="1312" alt="Screenshot 2020-06-06 at 01 25 31" src="https://user-images.githubusercontent.com/17012833/83929734-b57ba880-a794-11ea-9c9e-c3ce0911ddce.png">

I did also notice that the documentation says it's for version 0.9.0 even though pip installs 0.8.2. I'm not sure that might have something to do with it.

**Comment by julianoes** [comment]
Thanks for the not. I thought I had fixed it but this doesn't look like it.
0.9.0 is in fact the new one released on PyPi but it might not be depending on your platform, e.g. on arm.

**Comment by julianoes** [comment]
It works locally but fails in CI:
https://travis-ci.org/github/mavlink/MAVSDK-Python/jobs/694956963#L629-L631
