### ISSUE TITLE
MAVSDK-Python is compatible with ArduPilot?

### ISSUE THREAD

**Issue by MuhammadBilal1** [mavlink/MAVSDK-Python#229]
Hi,
I know the MAVSDK-Python is tested against PX4 and its compatible with that.
But for some reasons I need to use ArduPilot (ChibiOS or NuttX) firmware over the PixHawk4.

**Is the ArduPilot (ChibiOS or NuttX) compatible with MAVSDK-Python?**
If yes, is the [API reference documentation](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/) is same for both?

**Comment by julianoes** [comment]
Check this: https://github.com/mavlink/MAVSDK/issues/728
