### ISSUE TITLE
goto_location results in the aircraft descending to 0m alt and crashing

### ISSUE THREAD

**Issue by iwishiwasaneagle** [mavlink/MAVSDK-Python#233]
I have tried the following multiple times, with varying altitudes and airframes (Iris and Plane). However each time this is called, the UAV seemingly just descends until it lands.

```python
#!/usr/bin/env python3

import asyncio
from mavsdk import System, mission_raw

async def run():
    drone = System()
    await drone.connect(system_address="udp://:14540")

    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"Drone discovered with UUID: {state.uuid}")
            break
    
    await drone.action.goto_location(55.8688660,-4.2851267,40,0)

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
```

System:
 - Ubuntu 18.04 LTS
 - Gazebo 9
 - PX4 master

**Comment by JonasVautherin** [comment]
That's interesting :sweat_smile:. I think it was used successfully for a multicopter from Java. Are you sure that SITL is not just losing data link and hence doing RTL?

Because your script above will send the `goto` command and terminate, effectively terminating the MAVLink connection. Can you try to add `await asyncio.sleep(20)` after `await drone.action.goto_location(...)` to confirm that it still lands in that case?

**Comment by iwishiwasaneagle** [comment]
Yeah no dice even with `await asyncio.sleep(60)`... only log message I see is `INFO [Commander] Freefall detected` until it lands. I tried calling the `goto` during 3 different "states": during a mission, at the end of a completed mission, during a hold after manually flying the iris with a xbox controller.

**Comment by JonasVautherin** [comment]
I just tried your code above with `px4-gazebo-headless`, checking the status from QGC:

```
docker run --rm -it jonasvautherin/px4-gazebo-headless:latest
```

It seemed like it was working (at least it was flying north-west from Zurich :laughing:).
Would you mind trying it there, too? Just to check what happens when we use the same SITL version.

**Comment by iwishiwasaneagle** [comment]
That seems to work (I'm not waiting to see if it flys from Zurich to Glasgow hahaha!) in the docker container, but still not in a fresh VM with the most recent PX4/Firmware.

**Comment by JonasVautherin** [comment]
Hmm ok, so apparently something changed in PX4. Question now is whether that's a bug in PX4 or in MAVDSK.

**Comment by iwishiwasaneagle** [comment]
What's changed?

**Comment by julianoes** [comment]
> `INFO [Commander] Freefall detected`

:astonished: that doesn't sound good! Let me try to reproduce...

**Comment by julianoes** [comment]
This works for correctly me against PX4 master.

Can you share a log where it crashes for you?

**Comment by iwishiwasaneagle** [comment]
> This works for correctly me against PX4 master.
> 
> Can you share a log where it crashes for you?

Setup:

- Ubuntu 18.04 LTS
- PX4 master
- goto.py example you've just added https://github.com/mavlink/MAVSDK-Python/pull/234

I run the PX4 SITL with `make px4_sitl gazbo_plane` (after building with `DONT_RUN=1 make px4_sitl gazbo_plane`), then run `python3 goto.py`. Below are the relevant logs:

Something else to note is that I saw the same behavior when running
```python
pos = offboard.PositionNedYaw(1000,0,0,0)
log.debug(f"Beginning offboard control: {pos}")
await drone.offboard.set_position_ned(offboard.PositionNedYaw(0.0, 0.0, 0.0, 0.0))
await drone.offboard.start()
await drone.offboard.set_position_ned(pos)
```

```
$ make px4_sitl gazbo_plane
[0/4] Performing build step for 'sitl_gazebo'
ninja: no work to do.
[2/4] No install step for 'sitl_gazebo'
[3/4] Completed 'sitl_gazebo'
[3/4] cd /vagrant/Firmware/build/px4_sitl_default/tmp && /vagrant/Firmware/Tools/sitl_run.sh /vagrant/Firmware/build/px4_sitl_default/bin/px4 none gazebo plane none /vagrant/Firmware /vagrant/Firmware/build/px4_sitl_default
SITL ARGS
sitl_bin: /vagrant/Firmware/build/px4_sitl_default/bin/px4
debugger: none
program: gazebo
model: plane
world: none
src_path: /vagrant/Firmware
build_path: /vagrant/Firmware/build/px4_sitl_default
GAZEBO_PLUGIN_PATH :/vagrant/Firmware/build/px4_sitl_default/build_gazebo
GAZEBO_MODEL_PATH :/vagrant/Firmware/Tools/sitl_gazebo/models
LD_LIBRARY_PATH :/vagrant/Firmware/build/px4_sitl_default/build_gazebo
empty world, setting empty.world as default
not running gazebo gui
SITL COMMAND: "/vagrant/Firmware/build/px4_sitl_default/bin/px4" "/vagrant/Firmware"/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t "/vagrant/Firmware"/test_data
INFO  [px4] Creating symlink /vagrant/Firmware/ROMFS/px4fmu_common -> /vagrant/Firmware/build/px4_sitl_default/tmp/rootfs/etc

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
INFO  [param] selected parameter default file eeprom/parameters_1030
[param] parameter file not found, creating eeprom/parameters_1030
  SYS_AUTOCONFIG: curr: 0 -> new: 1
* SYS_AUTOSTART: curr: 0 -> new: 1030
  BAT_N_CELLS: curr: 0 -> new: 3
  CAL_ACC0_ID: curr: 0 -> new: 1311244
  CAL_ACC_PRIME: curr: 0 -> new: 1311244
  CAL_GYRO0_ID: curr: 0 -> new: 1311244
  CAL_GYRO_PRIME: curr: 0 -> new: 1311244
  CAL_MAG0_ID: curr: 0 -> new: 197388
  CAL_MAG_PRIME: curr: 0 -> new: 197388
  CBRK_SUPPLY_CHK: curr: 0 -> new: 894281
  COM_RC_IN_MODE: curr: 0 -> new: 1
  EKF2_ANGERR_INIT: curr: 0.1000 -> new: 0.0100
  EKF2_GBIAS_INIT: curr: 0.1000 -> new: 0.0100
  COM_ARM_EKF_AB: curr: 0.0022 -> new: 0.0050
  EKF2_REQ_GPS_H: curr: 10.0000 -> new: 0.5000
  MC_PITCH_P: curr: 6.5000 -> new: 6.0000
  MC_PITCHRATE_P: curr: 0.1500 -> new: 0.2000
  MC_ROLL_P: curr: 6.5000 -> new: 6.0000
  MC_ROLLRATE_P: curr: 0.1500 -> new: 0.2000
  MPC_Z_VEL_P_ACC: curr: 4.0000 -> new: 12.0000
  MPC_Z_VEL_I_ACC: curr: 2.0000 -> new: 3.0000
  MPC_XY_P: curr: 0.9500 -> new: 0.8000
  MPC_XY_VEL_P_ACC: curr: 1.8000 -> new: 4.0000
  MPC_XY_VEL_D_ACC: curr: 0.2000 -> new: 0.3200
  RTL_RETURN_ALT: curr: 60.0000 -> new: 30.0000
  SDLOG_MODE: curr: 0 -> new: 1
  SDLOG_PROFILE: curr: 3 -> new: 131
  SDLOG_DIRS_MAX: curr: 0 -> new: 7
  SENS_BOARD_X_OFF: curr: 0.0000 -> new: 0.0000
  SENS_DPRES_OFF: curr: 0.0000 -> new: 0.0010
  TRIG_INTERFACE: curr: 4 -> new: 3
  COM_CPU_MAX: curr: 90.0000 -> new: -1.0000
  IMU_INTEG_RATE: curr: 200 -> new: 250
  COM_POS_FS_DELAY: curr: 1 -> new: 5
  COM_POS_FS_EPH: curr: 5.0000 -> new: 15.0000
  COM_POS_FS_EPV: curr: 10.0000 -> new: 30.0000
  COM_POS_FS_GAIN: curr: 10 -> new: 0
  COM_POS_FS_PROB: curr: 30 -> new: 1
  COM_VEL_FS_EVH: curr: 1.0000 -> new: 5.0000
  EKF2_ARSP_THR: curr: 0.0000 -> new: 8.0000
  EKF2_FUSE_BETA: curr: 0 -> new: 1
  EKF2_GPS_CHECK: curr: 245 -> new: 21
  EKF2_MAG_ACCLIM: curr: 0.5000 -> new: 0.0000
  EKF2_MAG_YAWLIM: curr: 0.2500 -> new: 0.0000
  EKF2_REQ_EPH: curr: 3.0000 -> new: 10.0000
  EKF2_REQ_EPV: curr: 5.0000 -> new: 10.0000
  EKF2_REQ_HDRIFT: curr: 0.1000 -> new: 0.5000
  EKF2_REQ_SACC: curr: 0.5000 -> new: 1.0000
  EKF2_REQ_VDRIFT: curr: 0.2000 -> new: 1.0000
  RTL_TYPE: curr: 0 -> new: 1
* RTL_RETURN_ALT: curr: 30.0000 -> new: 100.0000
  RTL_DESCEND_ALT: curr: 30.0000 -> new: 100.0000
  MIS_LTRMIN_ALT: curr: -1.0000 -> new: 25.0000
  MIS_TAKEOFF_ALT: curr: 2.5000 -> new: 25.0000
  PWM_RATE: curr: 400 -> new: 50
  GPS_UBX_DYNMODEL: curr: 7 -> new: 8
  FW_LND_AIRSPD_SC: curr: 1.3000 -> new: 1.0000
  FW_LND_ANG: curr: 5.0000 -> new: 8.0000
  FW_THR_LND_MAX: curr: 1.0000 -> new: 0.0000
  FW_L1_PERIOD: curr: 20.0000 -> new: 15.0000
  FW_P_TC: curr: 0.4000 -> new: 0.5000
  FW_PR_FF: curr: 0.5000 -> new: 0.4000
  FW_PR_I: curr: 0.1000 -> new: 0.0500
  FW_PR_P: curr: 0.0800 -> new: 0.0500
  FW_R_TC: curr: 0.4000 -> new: 0.7000
  FW_RR_FF: curr: 0.5000 -> new: 0.2000
  FW_RR_I: curr: 0.1000 -> new: 0.0200
  FW_RR_P: curr: 0.0500 -> new: 0.2200
* FW_L1_PERIOD: curr: 15.0000 -> new: 12.0000
  FW_W_EN: curr: 0 -> new: 1
* MIS_LTRMIN_ALT: curr: 25.0000 -> new: 30.0000
* MIS_TAKEOFF_ALT: curr: 25.0000 -> new: 30.0000
  NAV_ACC_RAD: curr: 10.0000 -> new: 15.0000
  NAV_DLL_ACT: curr: 0 -> new: 2
  RWTO_TKOFF: curr: 0 -> new: 1
* SYS_AUTOCONFIG: curr: 1 -> new: 0
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
INFO  [simulator] Waiting for simulator to accept connection on TCP port 4560
INFO  [simulator] Simulator connected on TCP port 4560.
INFO  [commander] LED: open /dev/led0 failed (22)
  MAV_TYPE: curr: 2 -> new: 1
INFO  [init] Mixer: etc/mixers-sitl/plane_sitl.main.mix on /dev/pwm_output0
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 18570 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14580 remote port 14540
INFO  [mavlink] mode: Onboard, data rate: 4000 B/s on udp port 14280 remote port 14030
INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log (type: full)
INFO  [logger] [logger] ./log/2020-07-22/10_10_29.ulg
INFO  [logger] Opened full log file: ./log/2020-07-22/10_10_29.ulg
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [px4] Startup script returned successfully
pxh> INFO  [mavlink] partner IP: 10.0.2.2
INFO  [ecl/EKF] 860000: GPS checks passed
INFO  [ekf2] Mag sensor ID changed to 197388
INFO  [ecl/EKF] 3044000: EKF aligned, (baro hgt, IMU buf: 18, OBS buf: 14)
INFO  [ecl/EKF] 3044000: reset position to last known position
INFO  [ecl/EKF] 3044000: reset velocity to zero
INFO  [ecl/EKF] 5356000: reset position to GPS
INFO  [ecl/EKF] 5356000: reset velocity to GPS
INFO  [ecl/EKF] 5356000: starting GPS fusion
INFO  [mavlink] partner IP: 127.0.0.1
INFO  [commander] ARMED by Arm/Disarm component command
INFO  [navigator] Using minimum takeoff altitude: 30.00 m
INFO  [fw_pos_control_l1] Takeoff on runway
INFO  [commander] Takeoff detected
INFO  [runway_takeoff] #Takeoff airspeed reached
INFO  [runway_takeoff] #Climbout
INFO  [runway_takeoff] #Navigating to waypoint
INFO  [commander] Landing detected
INFO  [commander] DISARMED by Auto disarm initiated
INFO  [logger] closed logfile, bytes written: 2512406
INFO  [ecl/EKF] 68956000: reset velocity to GPS
INFO  [ecl/EKF] 68956000: reset position to GPS
WARN  [ecl/EKF] 68956000: GPS fusion timeout - reset to GPS
```

```
$ python3 goto.py 
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...
Drone discovered with UUID: 5283920058631409231
Waiting for drone to have a global position estimate...
Global position estimate ok
-- Arming
-- Taking off
```

Flight log: https://review.px4.io/plot_app?log=abaf850e-45f7-4084-b250-b089ba2ad1af

**Comment by julianoes** [comment]
Ok, thanks for all that info, that's very helpful. I had only tried `iris` before, not `plane`. I did a few tries and `plane` sometimes seemed to do the right thing and other times get too low and crash. For `iris` it now doesn't work anymore but just seems to go sideways at a weird angle, and keep going forever. It's very odd, I'm looking into it.

**Comment by iwishiwasaneagle** [comment]
> Ok, thanks for all that info, that's very helpful. I had only tried `iris` before, not `plane`. I did a few tries and `plane` sometimes seemed to do the right thing and other times get too low and crash. For `iris` it now doesn't work anymore but just seems to go sideways at a weird angle, and keep going forever. It's very odd, I'm looking into it.

Yeah that sums up the behavior nicely... I'm looking forward to hearing what the root cause was.

**Comment by julianoes** [comment]
Ok, I think the `iris` case actually makes sense. It goes the right direction but it does ignore the altitude. It just stays at whatever it was before which is wrong.

For `plane` it seems to work, however, you need to set the altitude correctly. The default SITL takeoff altitude in SITL is 488m, and the goto interface is in AMSL, so you need something > 488m.

**Comment by iwishiwasaneagle** [comment]
Ah good to know that it uses AMSL. It's probably worth stating that in the docs seeing as usual absolute altitude is used

**Comment by hamishwillee** [comment]
@julianoes @iwishiwasaneagle  The [docs/reference](https://mavsdk.mavlink.io/develop/en/api_reference/classmavsdk_1_1_action.html#classmavsdk_1_1_action_1a6fd615e5571d6e7e3c53a79d2160ffc5) do state that this is an absolute altitude, but the example does not.

FWIW IMO this API definition is a bug - the altitude should be relative to home, at very least "by default" (ideally we should even offer a terrain option). My reasoning is:
1. MAVSDK is supposed to be a simplification of MAVLINK - humans work in "above ground" frame, so forcing everyone to code in addition of ground is a pain. 
2. As a safety issue if you make the default relative to home, then if people don't read, then the vehicle won't crash.

Thoughts?

**Comment by julianoes** [comment]
@hamishwillee goto is based on https://mavlink.io/en/messages/common.html#MAV_CMD_DO_REPOSITION which unfortunately is specified in absolute altitude.

If we wanted to use relative altitude we would have to either:
1. Use the reposition flags or reserved param to indicate relative vs. absolute altitude. The problem here is that previous versions of PX4 would ignore that flag and land/crash.
2. Do the calculation based on home position. This would work, just requires the home position to be known before sending a goto. I can see how this would be safer.

**Comment by JonasVautherin** [comment]
> Do the calculation based on home position. This would work, just requires the home position to be known before sending a goto. I can see how this would be safer.

This makes sense to me. Would this imply adding a new action result, e.g. `RESULT_HOME_UNKNOWN`?

**Comment by hamishwillee** [comment]
So I like option 2, and yes, you'd want a new result(s)

But ideally while I would _default_ it to using home-based altitude I would not _restrict_ it to home because if terrain becomes available a lot of people will prefer that (and some might want AMSL). So if you can have a default and use home for that would be ideal.

And yes, you'd then probably have RESULT_HOME_UNKNOWN or RESULT_TERRAIN_UNKNOWN returned based on the type used.

**Comment by julianoes** [comment]
> This makes sense to me. Would this imply adding a new action result, e.g. RESULT_HOME_UNKNOWN?

I think so, yes.

> But ideally while I would default it to using home-based altitude I would not restrict it to home because if terrain becomes available a lot of people will prefer that (and some might want AMSL). So if you can have a default and use home for that would be ideal.

Fair enough, that would be nice.

I think we'll have to rename/change the existing function anyway though, otherwise existing users that use absolute altitude might suddenly be surprised.

I think we could change it to:
1. `goto_location_absolute_altitude()` and `goto_location_relative_altitude()`
2. ```
   enum AltitudeType {
       AboveHomePosition,
       AbsoluteAltitude,
       AboveTerrain
   };
   goto_location(..., AltitudeType altitude_type)
   ```

**Comment by JonasVautherin** [comment]
If it's just a matter of preferences, I like 1 better :innocent::

> 1. goto_location_absolute_altitude() and goto_location_relative_altitude()

**Comment by hamishwillee** [comment]
`goto_location_absolute_altitude()`, `goto_location_relative_altitude()` and later `goto_location_terrain_altitude()` OK by me.

**Comment by iwishiwasaneagle** [comment]
> `goto_location_absolute_altitude()`, `goto_location_relative_altitude()` and later `goto_location_terrain_altitude()` OK by me. Though perhaps `goto_location_home_rel_altitude()` - I've never particularly liked the use of "rel" with the thing that it is relative to not specified.

`goto_location_home_rel_altitude` is more intuitive than `goto_location_relative_altitude`

**Comment by julianoes** [comment]
Ok, good point @hamishwillee and @iwishiwasaneagle. In this case it I would suggest `goto_location_home_relative_altitude` :smiley:.

**Comment by iwishiwasaneagle** [comment]
Will `goto_location` be removed or maybe add a decorator like `@deprecated` [link](https://stackoverflow.com/a/40301488/4211488)?

**Comment by julianoes** [comment]
We might remove it because we haven't marked the API as stable yet, as it's not yet 1.0.0 (but hopefully soon).

**Comment by iwishiwasaneagle** [comment]
Getting this off my `issuse` log
