### ISSUE TITLE
Flight Mode error when running GoTo

### ISSUE THREAD

**Issue by deepak-1530** [mavlink/MAVSDK-Python#240]
When using drone.goto_location(lat, lon, alt, yaw) function, the flight mode of the drone (as seen by running telemetry_flight_mode.py script) is coming out to be HOLD whereas I need to have a separate flight mode for this. 

MAVSDK-Python version - 0.9.1

**Comment by JonasVautherin** [comment]
What do you mean by "I need to have a separate flight mode for this"? :thinking:

**Comment by deepak-1530** [comment]
I want to have a flight mode GOTO just as we have MISSION, OFFBOARD.

**Comment by julianoes** [comment]
Yes, that might make sense. Here is the PX4 discussion for this: https://github.com/PX4/Firmware/issues/14576

I'm closing this issue as it's not a MAVSDK issue.
