### ISSUE TITLE
Using subscriber in MAVSDK

### ISSUE THREAD

**Issue by HoJae-Lee1** [mavlink/MAVSDK-Python#248]
Hello,

Is there a way to use subscriber in MAVSDK?

I know subscriber is used in ROS and MAVSDK does not go through ROS, so it sounds nonsense.
However, I want to know if I can accomplish any similar function in any way.

The purpose is to acquire information from outside computers.(what I mean by 'outside computers' is computers other than px4 and ground station)

**Comment by julianoes** [comment]
You can combine all these pieces in C++ or Python as you want but I can't do it for you, sorry.
