### ISSUE TITLE
Failure Plugin Missing

### ISSUE THREAD

**Issue by petergerten** [mavlink/MAVSDK-Python#254]
I noticed that there are generated files for the Failure plugin, but it was not made available in system.
(I am a bit confused is the code in System supposed to be auto-generated as well?)

I created a PR https://github.com/mavlink/MAVSDK-Python/pull/253
which makes the Plugin available but then I noticed when using it I get:

```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:                              
        status = StatusCode.UNIMPLEMENTED  
```
I was assuming that all functionality from the core MAVSDK would be auto-generated for Python.

**Comment by JonasVautherin** [comment]
> I am a bit confused is the code in System supposed to be auto-generated as well?

Not, that's the one file that is not auto-generated :sweat_smile:. And also on the mavsdk-server side, plugins have to be manually added. That could be auto-generated, but it's not (somebody would need to put resources into that).

I notice now that the `failure` plugin is not enabled in `mavsdk_server`, which gives you the `UNIMPLEMENTED` error. Would you mind having a look? You should be able to just follow what the other plugins do, e.g. [here](https://github.com/mavlink/MAVSDK/blob/develop/src/backend/src/grpc_server.cpp#L21-L39), and maybe in a few other (non-autogenerated) files.

If you open a PR in the MAVSDK repo, we can guide you there :+1:.
