### ISSUE TITLE
Shell Command not working

### ISSUE THREAD

**Issue by nugustmd** [mavlink/MAVSDK-Python#311]
All drone connections have been verified, and other commands are working.

I want to send "**camera_trigger test**" with On the PX4 console command, but it doesn't work.

code: `drone.shell.send("camera_trigger test")`

Is there another way to utilize MAVSDK-Python to operate the Trigger Camera?

**Comment by JonasVautherin** [comment]
Are you running against SITL?

Not sure what this does. Isn't it equivalent to `drone.camera.take_photo()`?

**Comment by nugustmd** [comment]
@JonasVautherin 

It is actually being used in drones.

The drone.camera.take_photo() command does not work.

Do I need to set the camera separately for the drone.camera.take_photo() command to work?

If the camera_trigger test is performed in QGC after setting the current Trigger GPIO LOW Mode, it works normally.

**Comment by julianoes** [comment]
Right, `take_photo()` will likely not work as expected. It's a bit tricky because there are multiple interfaces to trigger photos with various support.

Do you know which message/command QGC uses to test it?

**Comment by nugustmd** [comment]
@julianoes 

No I don't know. Tried only take_photo().

The current drone camera settings are shown below.

How do I set it to use the take_photo() function?
![camera](https://user-images.githubusercontent.com/34853342/108955006-d54f5580-76b0-11eb-9e8c-811bf964bd37.PNG)


I want to use it as a GPIO trigger interface.

**Comment by JonasVautherin** [comment]
> How do I set it to use the take_photo() function?

`take_photo()` is a MAVSDK concept. Internally it sends `MAV_CMD_IMAGE_START_CAPTURE`, see [here](https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/camera/camera_impl.cpp#L210-L222):

```
MavlinkCommandSender::CommandLong CameraImpl::make_command_take_photo(float interval_s, float no_of_photos)
{
    MavlinkCommandSender::CommandLong cmd_take_photo{};

    cmd_take_photo.command = MAV_CMD_IMAGE_START_CAPTURE;
    cmd_take_photo.params.param1 = 0.0f; // Reserved, set to 0
    cmd_take_photo.params.param2 = interval_s;
    cmd_take_photo.params.param3 = no_of_photos;
    cmd_take_photo.params.param4 = float(_capture.sequence++);
    cmd_take_photo.target_component_id = _camera_id + MAV_COMP_ID_CAMERA;

    return cmd_take_photo;
}
```

**Comment by nugustmd** [comment]
Are there any commands that can perform Trigger Camera (Camera Test) in MAVSDK-Python?

I want to trigger the camera by sending a specific command, not distance or time.

**Comment by julianoes** [comment]
@nugustmd no that's currently not implemented. It's a bit unfortunate as there are several interfaces that could potentially be used.
