### ISSUE TITLE
do_orbit example

### ISSUE THREAD

**Issue by kwanyongcho7** [mavlink/MAVSDK-Python#322]
Hi, I want to use do_orbit action and need what to put in ??? part.

await drone.action.do_orbit(15, 2, ???, xstart, ystart, 30)

Is there  any examples of using do_orbit? 

I can't understand 

http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/action.html?highlight=orbit#mavsdk.action.OrbitYawBehavior

**Comment by JonasVautherin** [comment]
What the documentation you pointed to says is that this is the `OrbitYawBehavior`, "Yaw behaviour during orbit flight". It means that it tells the drone what to do with the yaw while orbiting. You can ask the drone to "look at the center of the orbit" (`HOLD_FRONT_TO_CIRCLE_CENTER`), keep the heading it had when it started the orbit (`HOLD_INITIAL_HEADING`), etc.

The way it works is that it is an enum you pass as a parameter. Probably something like:

```python
from mavsdk.action import OrbitYawBehavior

...

await drone.action.do_orbit(15, 2, OrbitYawBehavior.HOLD_FRONT_TO_CIRCLE_CENTER, xstart, ystart, 30)
```

**Comment by kwanyongcho7** [comment]
Thanks a lot.
