### ISSUE TITLE
goto_location makes drone height zero, parameters

### ISSUE THREAD

**Issue by kwanyongcho7** [mavlink/MAVSDK-Python#333]
I am using goto_location action to fly drone to specific location

await drone.action.goto_location(x, y, 31, degree)

but, sometimes It goes forward + down to zero height.

and about the yaw degree, is there any way i just make drone goes forward? like heading to?

**Comment by julianoes** [comment]
According to the [docs](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/action.html?highlight=goto#mavsdk.action.Action.goto_location) `goto_location` uses altitude in AMSL (above mean sea level). Are you sure you are setting the correct altitude?

To prevent yawing you should be able to set heading to NAN.

**Comment by kwanyongcho7** [comment]
So, I used drone.telemetry.home() terrain_info.absolute_altitude_m, and It works. However, Sometimes, drone goes too high.

**Comment by julianoes** [comment]
Is this outdoor with GPS or indoor?

**Comment by kwanyongcho7** [comment]
I think I solved it with refreshing terrain_info.absolute_altitude value when it starts each round.
