### ISSUE TITLE
failure inject

### ISSUE THREAD

**Issue by kwanyongcho7** [mavlink/MAVSDK-Python#335]
`await drone.failure.inject(mavsdk.failure.FailureUnit.SENSOR_MAG, mavsdk.failure.FailureType.OFF, 0)
`
I try to inject failure to my drone in Airsim, HITL.

`mavsdk.failure.FailureError: UNSUPPORTED: 'Unsupported'; origin: inject(); params: (<FailureUnit.SENSOR_MAG: 2>, <FailureType.OFF: 1>, 0)`

But, I got error message.

Is this my code problem or does my drone not support this failure?

**Comment by JonasVautherin** [comment]
> Is this my code problem or does my drone not support this failure?

Seems like the drone answered "UNSUPPORTED" :+1:

**Comment by julianoes** [comment]
The failures are only supported for SITL right now. This needs to be added to PX4 first.

**Comment by JonasVautherin** [comment]
Feels like this can be closed, feel free to reopen if necessary!
