### ISSUE TITLE
Cannot connect to mavlink-router

### ISSUE THREAD

**Issue by haiyu-zat** [mavlink/MAVSDK-Python#339]
Hi there,

I am trying to connect to mavlink-router using MAVSDK

When I use pymavlink's `mavutil.mavlink_connection("udp:0.0.0.0:14552")` I am able to receive heartbeats from the autopilot, but when I use `await drone.connect(system_address="udp:0.0.0.0:14552")`, I never get a response. Am I doing something wrong?

**Comment by JonasVautherin** [comment]
Yes, you should do something like:

```
await drone.connect(system_address="udp://:14552")
```

**Comment by haiyu-zat** [comment]
Ok thanks!
