### ISSUE TITLE
Telemetry returning value to RNU() loop

### ISSUE THREAD

**Issue by Hamidraei23** [mavlink/MAVSDK-Python#382]
Can You show mean example that how can I save a return value from telemetry async function to the main loop?
I have been trying it a lot but I am confused with async

**Comment by JonasVautherin** [comment]
Would something like this help? https://addshore.com/2018/06/python3-using-some-shared-state-in-2-async-methods/

**Comment by Hamidraei23** [comment]
Oh good, I found asyncio.gather but it did not work now I added await from the page that U just mentioned and it worked.
Thanks
