### ISSUE TITLE
CAN'T CONNECT WITH AIRSIM

### ISSUE THREAD

**Issue by RyanFoward** [mavlink/MAVSDK-Python#386]
Hello Jonas! I'm Ryan, and I'm part of a university team that works with autonomous drones.
We've had problems with connect mavsdk on windows to the simulator AirSim, we are using this lines of code:
```
drone = System()
    await drone.connect(system_address="udp://:14540")
```
but the only message that appears is:
```
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...
```
but never connect with the drone

What can we try?

**Comment by JonasVautherin** [comment]
Did you find a solution?

**Comment by RyanFoward** [comment]
Yes!! We find a way to do this connection! Thx Jonas!

**Comment by JonasVautherin** [comment]
Would you mind explaining here what was wrong and how you fixed it? So that it could help somebody else with the same issue? That's how it usually works :innocent:: you ask for help, and if you find the answer before somebody else can help you, you share it with the community :+1:
