### ISSUE TITLE
How to get messages/warning/errors in MAVSDK?

### ISSUE THREAD

**Issue by MuhammadBilal1** [mavlink/MAVSDK-Python#387]
Hi,
Is there a way in MAVSDK that can help us in getting the message/warnings/errors about the drone as we get in the QGroundControl/Mission planner?

For Example:
Critical Navigation Failure
Arming Denied
Failsafe enabled
etc.

Some messages can be seen on the attached images of QGC.

![Screenshot from 2021-08-27 07-52-09](https://user-images.githubusercontent.com/7131058/131287222-1eb6d04f-40a7-4ef9-90ed-7b6de4ee2b8c.png)

![Screenshot from 2021-08-27 07-53-12](https://user-images.githubusercontent.com/7131058/131287231-3d5f2b96-2d46-4f2f-aaf3-b123af71db0e.png)

![Screenshot from 2021-08-27 07-57-22](https://user-images.githubusercontent.com/7131058/131287233-ba9633d8-5003-476b-b848-ba73ecec7809.png)

**Comment by julianoes** [comment]
Try subscribing to status texts: http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/telemetry.html?highlight=statustext#mavsdk.telemetry.Telemetry.status_text

**Comment by MuhammadBilal1** [comment]
> Try subscribing to status texts: http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/telemetry.html?highlight=statustext#mavsdk.telemetry.Telemetry.status_text

This is what I was looking for. **It worked.**

Thank you.
