### ISSUE TITLE
Other examples in MAVSDK-Python can run perfectly but not manual_control.py example

### ISSUE THREAD

**Issue by kois86** [mavlink/MAVSDK-Python#393]
Hi,

I am at loss in troubleshooting the issue for my program. FYI, my program performs precision landing on a moving platform and for that, I use manual_control.py example.

I use HiTL setup whereby my Raspi, containing the program above, is connected to pixhawk FC, and this pixhawk is connected to the PC running Gazebo simulator.

FYI, what weird is, when i run my program, only drone.manual_control.set_manual_control_input() not running. Other instructions within the example, such as takeoff and land, and even drone.manual_control.start_position_control(), having an effect on the gazebo simulator.

Other examples such as offboard_attitude.py, telemetry_flight.py, all run well, only that instruction not working.

Anyone has the same issue or can solve my problem. Thank you in advance and please help as I really have no idea how to move forward on this. 

Thank you

**Comment by julianoes** [comment]
Thanks for the issue. I will have to try to reproduce it sometime.

For precision landing I would suggest to use offboard rather than manual control though.

**Comment by julianoes** [comment]
> require precision pitch yaw roll and throttle control.

You can do that with offboard attitude control: https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_offboard.html#classmavsdk_1_1_offboard_1af6f0d3991bb6b62f39d862c46fcffb34

**Comment by kois86** [comment]
Hi Julian,

have u tested the manual control? when i go through the documentation i found this

[](http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/manual_control.html#mavsdk.manual_control.ManualControl.set_manual_control_input)async set_manual_control_input(x, y, z, r)
Set manual control input

**The manual control input needs to be sent at a rate high enough to prevent triggering of RC loss, a good minimum rate is 10 Hz.**

Which I think is the cause of the API not running. is there a way to override or to adjust the 10hz fast rate input requirement?

**Comment by JonasVautherin** [comment]
Well you have to call the function, if you want to call it at 20Hz that's on your end, right?

**Comment by kois86** [comment]
Programming wise, i have run the examples given in the github repository, refer to https://github.com/mavlink/MAVSDK-Python/blob/main/examples/manual_control.py.

when running the program in simulation together with QGroundControl as monitoring, the drone will enter position mode and then it will do nothing. but will move accordingly when I run it without.

Thus, when I want to test onto the actual drone, it will not move similar to the simulation - it just only enter position mode

**Comment by kois86** [comment]
anyhow, have u tried the example with QGC?

thank you very much

**Comment by JonasVautherin** [comment]
> but will move accordingly when I run it without.

You mean the mavsdk example works if QGC is not connected, but it fails if QGC is connected?

**Comment by kois86** [comment]
> > but will move accordingly when I run it without.
> 
> You mean the mavsdk example works if QGC is not connected, but it fails if QGC is connected?

Yes, exactly. with QGC connected, the drone doesnt move accordingly and just descend until it lands

**Comment by JonasVautherin** [comment]
Do you have the virtual joysticks enabled in QGC? Could it be interfering somehow?

**Comment by kois86** [comment]
> Do you have the virtual joysticks enabled in QGC? Could it be interfering somehow?

I have disabled the virtual joystick, but unfortunately to a same result.

Any idea why i cant use the example with QGC connected?

**Comment by JonasVautherin** [comment]
Feels like some kind of interference at the mavlink level :thinking:. Would be nice to understand why, if you can have a closer look :+1:

**Comment by kois86** [comment]
I did try to troubleshoot and have a closer look but can only think this requirement _(The manual control input needs to be sent at a rate high enough to prevent triggering of RC loss, a good minimum rate is 10 Hz)_ that prevent the example to run.

the reason I prefer the manual control over offboard attitude is that it gives natural smooth movement of the drone without the need to put in await asyncio.sleep after the instruction to make it move, which lead to two problems that I encountered when using offboard attitude:

1. jerking movement as there are pauses between each set of offboard movement instructions
2. latency of the real-time input(in my case camera feed) that reduce the accuracy of the program. 

However, currently I'm still using offboard attitude for my actual drone, while still looking for a way to use manual control. do feedback if you have any idea, or example of manual control being used in the actual drone which requires QGC in the loop.

thank you

**Comment by julianoes** [comment]
@kois86 which PX4 version are you using? And what is your param https://docs.px4.io/master/en/advanced_config/parameter_reference.html#COM_RC_IN_MODE?

**Comment by julianoes** [comment]
Closing, as there was no more follow up.

**Comment by kennethakiti1** [comment]
has anyone found a way to get the manual_control to work?

**Comment by julianoes** [comment]
@kennethakiti1 please create a new issue with whatever does not work as it should for you please.
