### ISSUE TITLE
Command Denied When Running takeoff_and_land

### ISSUE THREAD

**Issue by ltrogers98** [mavlink/MAVSDK-Python#405]
Hello,

I am trying to run takeoff_and_land from my windows computer to get my px4 drone to takeoff and land. It is connected via the telemetry radio to the PC. The drone prints the following 

-- Connected to drone!
-- Arming

mavsdk.action.ActionError: COMMAND_DENIED: 'Command Denied'; origin: arm(); params: ()

So the drone connects but it will not arm with the code. Not sure what is happening. 

I eventually want to control the drone via a joystick connected to my PC. I am not sure what is going on. Can anyone help. In Q Ground Control it arms when I use the virtual joystick but not the physical joystick with the RC mode set to joystick. 

Thanks.

**Comment by julianoes** [comment]
Try to get some more log information using this change: https://github.com/mavlink/MAVSDK-Python/pull/370#pullrequestreview-729712188

Hopefully that will tell you why it doesn't arm.

Note to self: we should add docs how to do that.

**Comment by julianoes** [comment]
There was no follow up, closing.

And here is a PR that should help with this: https://github.com/mavlink/MAVSDK-Python/pull/467.
