### ISSUE TITLE
Can I use mavsdk to communicate through the same network (wifi)?

### ISSUE THREAD

**Issue by JinraeKim** [mavlink/MAVSDK-Python#414]
Hi,
I'm a newbie of mavsdk, so I don't get it whether it's possible to communicate between an RPi and a laptop, which shares the same wifi network.

The reason why I'm confused is, the tutorial example's `network_address` is always about udp.

**Comment by julianoes** [comment]
What are you trying to achieve? And where is your MAVSDK running, on the RPi or on the laptop?

**Comment by JinraeKim** [comment]
> 

RPi is a companion computer communicating with Pixhawk, and MAVSDK is probably running on the RPi.
Laptop is regarded as a GCS, receiving some data from RPi.

**Comment by julianoes** [comment]
Sorry, I missed your answer here. I assume you have resolved the problem by now, and I'm closing this.
