### ISSUE TITLE
How to connect Pixhawk to a Mac laptop and receive data using MAVSDK?

### ISSUE THREAD

**Issue by JinraeKim** [mavlink/MAVSDK-Python#415]
Hi, developers!

I'd like to know how to connect Pixhawk (4) to my M1 Macbook Air and receive data using MAVSDK?
I found an issue (#84), seems to be related to my situation, but `start_mavlink()` is not supported anymore.

I also tried to replace it by `await drone.connect(system_address="serial:///dev/ttyUSB0:57600")`, but it does not work.

Thanks in advance :)

**Comment by JinraeKim** [comment]
I found the solution.
You can find a related USB modem (?), which is in `/dev`.
For example, in my case, the following change makes it work:
`await drone.connect(system_address="serial:///dev/tty.usbmodem01")`

**Comment by julianoes** [comment]
Thanks for following up. Yes, that's right, for macOS. So this works now and the issue can be closed?

**Comment by JinraeKim** [comment]
@julianoes Of course. I closed this issue with this comment.
