### ISSUE TITLE
ImportError mavsdk-0.22.0

### ISSUE THREAD

**Issue by Jai-GAY** [mavlink/MAVSDK-Python#416]
Traceback (most recent call last):
  File "arm_quad_mavsdk.py", line 4, in <module>
    from mavsdk import System
  File "/home/pi/.local/lib/python3.7/site-packages/mavsdk/__init__.py", line 7, in <module>
    from .system import System
  File "/home/pi/.local/lib/python3.7/site-packages/mavsdk/system.py", line 6, in <module>
    from .async_plugin_manager import AsyncPluginManager
  File "/home/pi/.local/lib/python3.7/site-packages/mavsdk/async_plugin_manager.py", line 3, in <module>
    import aiogrpc
  File "/home/pi/.local/lib/python3.7/site-packages/aiogrpc/__init__.py", line 1, in <module>
    from grpc import ChannelConnectivity, StatusCode, RpcError, RpcContext,\
  File "/home/pi/.local/lib/python3.7/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/home/pi/.local/lib/python3.7/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
**ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/pi/.local/lib/python3.7/site-packages/grpc/_cython/cygrpc.cpython-37m-arm-linux-gnueabihf.so)**

###################################################################
pip3 install mavsdk

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mavsdk
  Downloading https://files.pythonhosted.org/packages/c8/80/0606a608ff7aafb63e051358992cb860bef583162c202aaab1cfb824c8df/mavsdk-0.22.0-py3-none-linux_armv7l.whl (11.1MB)
Collecting aiogrpc>=1.5 (from mavsdk)
  Downloading https://files.pythonhosted.org/packages/16/db/bd010b6fed762952142100da5707a769143af7a1795caa8d8bdff9d9ca85/aiogrpc-1.8-py3-none-any.whl
Collecting grpcio>=1.11.0 (from mavsdk)
  Downloading https://files.pythonhosted.org/packages/6c/41/54fca86bc86725ef3e42bb15af905949278181694d689bc47cfa9112d93a/grpcio-1.42.0-cp37-cp37m-linux_armv7l.whl (50.1MB)
Collecting protobuf>=3.13.0 (from mavsdk)
  Downloading https://files.pythonhosted.org/packages/c1/12/7479ece04931984162698bfaa05cbb2fc23d7f6ee1ab5146cfc6ade56a31/protobuf-3.19.1-py2.py3-none-any.whl (162kB)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio>=1.11.0->mavsdk) (1.12.0)
Installing collected packages: grpcio, aiogrpc, protobuf, mavsdk
Successfully installed aiogrpc-1.8 grpcio-1.42.0 mavsdk-0.22.0 protobuf-3.19.1
###################################################################
Python 3.7.3
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by julianoes** [comment]
Can you try to update `grpc` installed via pip?

```
pip3 install --user --upgrade grpc
```

Which Raspberry Pi is this?

**Comment by Jai-GAY** [comment]
> Which Raspberry Pi is this?

Pi4B

okay, later or tomorrow I try

**Comment by julianoes** [comment]
https://groups.google.com/g/grpc-io/c/T91EyO81c8I

**Comment by Jai-GAY** [comment]
> https://groups.google.com/g/grpc-io/c/T91EyO81c8I

ldd --version
ldd (Debian GLIBC 2.28-10+rpt2+rpi1) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

likely no luck for pip3 install --user --upgrade grpc

**Comment by Jai-GAY** [comment]
> pip3 install --user --upgrade grpc

$ pip3 install --user --upgrade grpc
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting grpc
  Downloading https://files.pythonhosted.org/packages/af/e6/59c8758fbb536a430c4409fba4098017d463a408858099e86ec1c96ab8fe/grpc-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-frbx0r22/grpc/setup.py", line 33, in <module>
        raise RuntimeError(HINT)
    RuntimeError: Please install the official package with: pip install grpcio

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-frbx0r22/grpc/

**Comment by julianoes** [comment]
@ferglezr1998 thanks for the note. Which RPi and which RPi OS was that?

**Comment by ferglezr1998** [comment]
@julianoes  I'm using Rpi 4B with Raspbian 10. And I have glibc 2.28 instead 2.29 that was required by grpc

**Comment by julianoes** [comment]
Ok thanks.

I think in the past it worked well when I used python grpc as shipped by deb, I think `sudo apt install python3-grpcio`.

**Comment by Jai-GAY** [comment]
Thank you so much for the pointers and apologies for the delay in responding.

In Pi Buster, as suggested, I uninstalled 1.42 and downgraded it to 1.40.0 for Python 3.7.
Now, I am[ having other issues](https://github.com/mavlink/MAVSDK-Python/issues/453#issuecomment-1108217843).
Interestingly, this does not happen in Pi Bullseye Pythom 3.9 with 1.43.0

sudo pip3 install grpcio==1.40.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting grpcio==1.40.0
  Downloading https://files.pythonhosted.org/packages/3f/c0/2922ed9b88adf7bea8d0d12870a3528f043ed90d1a6d0de6fde6cf3f5826/grpcio-1.40.0-cp37-cp37m-linux_armv7l.whl (38.4MB)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio==1.40.0) (1.12.0)
Installing collected packages: grpcio
  Found existing installation: grpcio 1.16.1
    Not uninstalling grpcio at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'grpcio'. No files were found to uninstall.
Successfully installed grpcio-1.40.0

Name: grpcio
Version: 1.43.0
Summary: HTTP/2-based RPC framework
Home-page: https://grpc.io
Author: The gRPC Authors
Author-email: grpc-io@googlegroups.com
License: Apache License 2.0
Location: /home/pi/.local/lib/python3.9/site-packages
Requires: six
Required-by: mavsdk, aiogrpc
