### ISSUE TITLE
Why doesn't the second Command of「offboard.set_position_ned」work?

### ISSUE THREAD

**Issue by moshibe** [mavlink/MAVSDK-Python#423]
I tried drone control by Offboard.
Command of「offboard.sset_position_ned」 didn't.
There was no error to give command, but the ｄrone was not moving.
Finally, the dorone landed successfully.
Why doesn't the second Command of「offboard.sset_position_ned」work?
※A guard timer of 10 seconds is set between commands.

①　drone.action.arm()
➁　drone.action.takeoff()　
➂　drone.offboard.set_position_ned()
④　drone.offboard.set_position_ned()
⑤　drone.action.land()

 please tell me how to do this?

**Comment by julianoes** [comment]
It's hard or impossible to say based on this information, I'm afraid. In order to understand what is happening I would need to see the code that is running as well as a logfile of the flight. You can upload the log to logs.px4.io and then link it here.

**Comment by moshibe** [comment]
Thank you for your answer. 
I am sorry for the insufficient information. 
We are using SITL Simulator (Software in the Loop). 
The code is compressed in a zip file. 
Thank you for your cooperation.

[test02.zip](https://github.com/mavlink/MAVSDK-Python/files/7779516/test02.zip)

**Comment by moshibe** [comment]
Thank you for your answer. 
I'm sorry, I don't have enough information. 
I an using SITL Simulator (Software in the Loop). 
I have attached the source code in compressed form. 
Thank you very much for your help.

 [test02.zip](https://github.com/mavlink/MAVSDK-Python/files/7779615/test02.zip)

**Comment by julianoes** [comment]
Can you create a logfile of when it does not work? The logs are saved in `build/px4_sitl_default/tmp/rootfs/log/` of the PX4 directory.

**Comment by moshibe** [comment]
Thank you for your answer. 
I can't find the folder you specified. 
I found the logs in the following folder, which is attached. 

C:\ardupilot\ArduCopter\mav.tlog 
C:\ardupilot\ArduCopter\logs\LASTLOG.TXT
[log.zip](https://github.com/mavlink/MAVSDK-Python/files/7782831/log.zip)

**Comment by moshibe** [comment]
My environment
PC Windows10 
simulator SITL Simulator (Software in the Loop) 
mavsdk 0.22.0.

**Comment by moshibe** [comment]
My goal is to move the drone. 
Is it possible to use another command to move the drone instead of this "offboard.set_position_ned"?

**Comment by julianoes** [comment]
Ok, it looks like you are using ArduPilot. Note that MAVSDK does not support ArduPilot fully. For a list of what is supposed to work, check https://github.com/mavlink/MAVSDK/issues/1568.

Also, you're version 0.22.0 is very old, make sure to use the latest one.

**Comment by julianoes** [comment]
As you can see in https://github.com/mavlink/MAVSDK/issues/1568, offboard/guided support is not yet supported in MAVSDK for ArduPilot. You have to either debug it yourself or use something else like e.g. DroneKit.

**Comment by moshibe** [comment]
Thank you for your answer. 
I understood that the MAVSDK does not support ArduPilot. 

Please let me know about dronekit-android. 
I am not able to find the documentation of the API in the following URL. 
https://github.com/dronekit/dronekit-android
Do you know, where is the documentation of the API?

**Comment by julianoes** [comment]
I don't know. I'd have to google it as well.
