### ISSUE TITLE
offboard position or attitude setpoints for fixedwing in mavsdk

### ISSUE THREAD

**Issue by airsimdevdd** [mavlink/MAVSDK-Python#429]
Is fixedwing supports position and attitude setpoints in mavsdk ?

**Comment by julianoes** [comment]
The question is whether it is supported in PX4. Let's see if @Jaeyoung-Lim knows.

**Comment by Jaeyoung-Lim** [comment]
@julianoes Explained in https://github.com/PX4/PX4-Autopilot/issues/18961 !

**Comment by julianoes** [comment]
Thanks @Jaeyoung-Lim.
