### ISSUE TITLE
Can't go through waypoints on Fixed Wing

### ISSUE THREAD

**Issue by Erush01** [mavlink/MAVSDK-Python#444]
I'm trying to do a autonomous 8 figure with Fixed Wing using MAVSDK-Python with PX4. When I use goto_location() it loiters around that waypoint. How can I make it go through waypoints.
![Screenshot from 2022-02-20 12-14-28](https://user-images.githubusercontent.com/69166608/154838912-89ee176d-1413-4e58-b808-bbab906b77d8.png)
.

**Comment by JonasVautherin** [comment]
Did you try planning a mission?

**Comment by Erush01** [comment]
> 
![Screenshot from 2022-02-21 01-32-3
![Screenshot from 2022-02-21 01-32-14](https://user-images.githubusercontent.com/69166608/154954627-2a8434a6-67f7-450c-bb4c-833213cbe175.png)
![Screenshot from 2022-02-20 13-01-23](https://user-im
![Screenshot from 2022-02-20 12-58-36](https://user-images.githubusercontent.com/69166608/154954678-e106b76a-6acb-43d6-a16e-44a6ff8e4f35.png)
ages.githubusercontent.com/69166608/154954668-0bb37b94-94b7-4e6c-8e0d-60e7bde6f5b5.png)

2](https://user-images.githubusercontent.com/69166608/154954568-393442bd-a9ab-40a7-9941-c9f85ef72a64.png)

I tried with both QGroundControl and from code. I think I did something wrong but I dont know what it is.

**Comment by Erush01** [comment]
> Did you try planning a mission?

I tried to set a plan with both QGroundControl and from code. But both didnt worked like as I expected. 

![Screenshot from 2022-02-20 13-01-23](https://user-images.githubusercontent.com/69166608/154954982-3217ed88-8681-4f34-9eeb-f2f71abdbe50.png)

![Screenshot from 2022-02-20 12-58-36](https://user-images.githubusercontent.com/69166608/154955009-ba6ab3be-fdfa-4e94-aace-b1669a1c7a87.png)

![Screenshot from 2022-02-21 01-32-32](https://user-images.githubusercontent.com/69166608/154955030-ac80b8e0-39ed-4352-84f1-fac163436a2f.png)



![Screenshot from 2022-02-21 01-32-14](https://user-images.githubusercontent.com/69166608/154955074-997c1cf6-f051-48f0-9014-3a22fce07fe5.png)

**Comment by JonasVautherin** [comment]
I guess the fixed wing has some limitations on the curves it can fly, and depending on how the waypoints are set, it won't be able to fly directly from one to the other.

If you don't care too much about where the waypoints are, another way to make an 8 figure would be to use the offboard mode, I would say.

**Comment by MehdiRifi** [comment]
Fixed wings vehicles can't hover on a position like copter, so only 4 choices are possible:

- loiter around the given waypoint
- continue to the next waypoint 
- land at the given waypoint
- return to launch

when planning a mission pay attention to the radius of the waypoints if it is big enough that circles will cut each other you will get the something similar as you're last picture.

decrease the waypoint radius, no idea where to find it in qgroundcontrol but in mission planner you will find it as follow :
![missionplanner1](https://user-images.githubusercontent.com/37449931/155029378-07c30fd5-48e3-45ad-8884-1478b5af8116.png)

the bigger the distance the accurate the behavior you will have based on my experience.

**Comment by julianoes** [comment]
I think you need to try to make the plan bigger, or reduce the radius that the plane can fly. I assume you are using ArduPilot, and not PX4?

Essentially, if you can make it work with MissionPlanner, then you should be able to set a mission with the exact same mission items using the `MissionRaw` plugin.

**Comment by julianoes** [comment]
There was no more follow up, so I'm closing this. Just comment again if this is still unresolved.
