### ISSUE TITLE
MAVSDK Python -- Flying an imported Q Ground Control Mission

### ISSUE THREAD

**Issue by StavrosKontzias29** [mavlink/MAVSDK-Python#458]
Hello,

Working with MAVSDK for my senior capstone project. Tested multiple functions with MAVSDK such as arming the drone and the  Take Off and Land example given in the MAVSDK Python GitHub Page.  Currently, I am able to import a Q Ground Control Mission, but I am having issues to actually begin that flight mission. Figured I should just be able to run the "start_mission()" function but no luck and I am stuck. Any help would be appreciated!

Thank you

**Comment by julianoes** [comment]
Hi there,

What error do you see in Python when you try to start the mission? And if there error doesn't tell you anything, then you can try to get more output by following these steps: http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/#debug-connection-issues

**Comment by StavrosKontzias29** [comment]
So I originally tried to use the the line  "  await drone.mission.start_mission(mission_import_data) " assuming that would run the mission. I do know this is incorrect, the error I got from python was " await drone.mission.start_mission(mission_import_data) NameError: name 'mission_import_data' is not defined. I've also attached the code I am using. We are using a raspberry pi 4 as an onboard computer to run the code. Like I mentioned before we were able to run the takeoff and Land example on our drone  without any issues so am assuming I am missing something needed to actually begin the flight of the QGC mission in my code.
 Below is the code we have been trying to get to work
Thank you again!


import asyncio
from mavsdk import System

drone = System()


# Connect to Flight Controller on ACM0
async def connect():
    print("--Looking for the drone now")
    await drone.connect(system_address="serial:///dev/ttyACM0")


# Verify Connection to Flight Controller
async def check_drone_connection():
    await connect()
    print("---Waiting for drone.")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"--Drone discovered")
            break


# Check GPS Connection
async def check_gps():
    await connect()
    print("--Waiting for drone to have global position")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok:
            print(f"--Global position estimate ok")
            break


# Arm Drone
async def arm_drone():
    print("-- Arming")
    await drone.action.arm()


# Import QGC flight mission
async def import_flight_mission():
    print("-- Uploading Mission")
    mission_import_data = await drone.mission_raw.import_qgroundcontrol_mission("flight_mission.plan")
    print(f"{len(mission_import_data.mission_items)} mission items imported")
    await drone.mission_raw.upload_mission(mission_import_data.mission_items)
    print("-- Mission uploaded")


# Run imported mission
async def run_imported_mission():
    print("-- Starting Mission")
    await drone.mission.start_mission()


# Run Drone
async def run_drone():
    await connect()
    await check_drone_connection()
    await import_flight_mission()
    await arm_drone()
    await run_imported_mission()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run_drone())

**Comment by julianoes** [comment]
Ok, so what error do you see with this?

And have you tried to get more debugging output as described in: http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/#debug-connection-issues

**Comment by StavrosKontzias29** [comment]
Yes I did try the steps on the link you attached and we don’t have any connection issues. I’m attaching a picture of the error output I meant to put that in my last post. Sorry that the image is a little blurry

![49332932-5756-40D0-9E8B-F1F754474D75](https://user-images.githubusercontent.com/85579480/160692435-b302bd91-3743-4e13-8a3a-c6fca2897dab.jpeg)

**Comment by julianoes** [comment]
You know you can take screenshots directly ;) Can you run mavsdk_server separate and share the output of it? That would probably help.

**Comment by StavrosKontzias29** [comment]
Haha ye I am well aware I was in a hurry and all I had was the photo on my phone. But here is the output for mavsdk_server

![Mavsdkserver](https://user-images.githubusercontent.com/85579480/160700839-a098b024-f05d-4b50-9e87-f249869ba7ee.PNG)
r

**Comment by StavrosKontzias29** [comment]
So we ran our code and mavsdk_server separately while it was running and this is the output on the server for the first image. Second image is just the full output from mavsdk_server

![MAVSDKCODEANDTERMINAL](https://user-images.githubusercontent.com/85579480/160888672-2e0a44d4-490c-4e7f-aa46-98b49beacd9a.PNG)
![mavsdk-commandline-errors](https://user-images.githubusercontent.com/85579480/160889011-e2c5c7ef-e99e-4763-b88e-5d7c784e90da.PNG)
r

**Comment by julianoes** [comment]
Ok please also check if this is still the same with the latest version.

This should update it:
```
pip3 install --user --upgrade mavsdk
```

**Comment by StavrosKontzias29** [comment]
I was able to update mavsdk. Below is what mavsdk_server was showing. Key one I noticed was "Mission rejected: takeoff altitude too low".
![takeoffError](https://user-images.githubusercontent.com/85579480/161301832-9659ed17-0511-4306-8f76-caca10b06a8c.PNG)

**Comment by julianoes** [comment]
Ok, what is the takeoff altitude that you're trying to send? Or is maybe the frame incorrect?

**Comment by julianoes** [comment]
@StavrosKontzias29 can you share the QGC plan that you're using? That would allow me to reproduce it.

**Comment by StavrosKontzias29** [comment]
Hello, Sorry for the late response. We had the takeoff altitude too low once we changed it we were able to successfully fly the mission!!
