### ISSUE TITLE
Running on Raspberry Pi fails with `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by stan-humphries** [mavlink/MAVSDK-Python#487]
After installing MavSDK on a brand new Raspberry Pi, running the takeoff and land example fails with:

from grpc._cython import cygrpc
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/stan/.local/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so

Can anybody suggest a solution?

Thanks!
Stan

**Comment by julianoes** [comment]
Ok thanks for the note.

Make sure to check the output of the server as described here:
http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/#debug-connection-issues
