### ISSUE TITLE
failed to switch from takeoff to offboard_position_ned

### ISSUE THREAD

**Issue by kennethakiti1** [mavlink/MAVSDK-Python#505]
so I'm trying to use the offboard_position_ned to control the final landing of my drone to the desired position (manual control doesn't seem to work)
the example here [https://github.com/mavlink/MAVSDK-Python/blob/main/examples/offboard_position_ned.py](here)  seems to work, but when I begin it off by taking off to an altitude and setting that altitude to `offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))` the code doesn't work and it just lands after take off.

so for example 
```
#!/usr/bin/env python3

import asyncio

from mavsdk import System
from mavsdk.offboard import (OffboardError, PositionNedYaw)


async def run():
    
    drone = System()
    await drone.connect(system_address="serial:///dev/ttyACM0:115200")

    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"-- Connected to drone!")
            break

    print("Waiting for drone to have a global position estimate...")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok and health.is_home_position_ok:
            print("-- Global position estimate OK")
            break

    print("-- Arming")
    await drone.action.arm()

    print("-- Setting initial setpoint")
    await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))

    print("-- Starting offboard")
    try:
        await drone.offboard.start()
    except OffboardError as error:
        print(
            f"Starting offboard mode failed with error code: {error._result.result}")
        print("-- Disarming")
        await drone.action.disarm()
        return

    print("-- Go 0m North, 0m East, -5m Down within local coordinate system")
    await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, -5.0, 0.0))
    await asyncio.sleep(10)

    print("-- Go 5m North, 0m East, -5m Down within local coordinate system, turn to face East")
    await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))
    await asyncio.sleep(10)

    await drone.action.land()
    await asyncio.sleep(10)

    await drone.action.disarm()


    print("-- Stopping offboard")
    try:
        await drone.offboard.stop()
    except OffboardError as error:
        print(
            f"Stopping offboard mode failed with error code: {error._result.result}")


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
```

this example works well, but when i try a takeoff before beginning the offboard mode the drone just lands after takeoff.
example like in this code

```
#!/usr/bin/env python3

"""
Caveat when attempting to run the examples in non-gps environments:
`drone.offboard.stop()` will return a `COMMAND_DENIED` result because it
requires a mode switch to HOLD, something that is currently not supported in a
non-gps environment.
"""

import asyncio

from mavsdk import System
from mavsdk.offboard import (OffboardError, PositionNedYaw)


async def run():
    """ Does Offboard control using position NED coordinates. """

    drone = System()
    await drone.connect(system_address="serial:///dev/ttyACM0:115200")

    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"-- Connected to drone!")
            break

    print("Waiting for drone to have a global position estimate...")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok and health.is_home_position_ok:
            print("-- Global position estimate OK")
            break

    print("-- Arming")
    await drone.action.arm()

    print("-- Taking off")
    await drone.action.set_takeoff_altitude(20)
    await drone.action.takeoff()
    await asyncio.sleep(15)

    print("-- Setting initial setpoint")
    await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))

    print("-- Starting offboard")
    try:
        await drone.offboard.start()
    except OffboardError as error:
        print(
            f"Starting offboard mode failed with error code: {error._result.result}")
        print("-- Disarming")
        await drone.action.disarm()
        return

    print("-- Go 0m North, 0m East, -5m Down within local coordinate system")
    await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, -5.0, 0.0))
    await asyncio.sleep(10)

    print("-- Go 5m North, 0m East, -5m Down within local coordinate system, turn to face East")
    await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))
    await asyncio.sleep(10)

    await drone.action.land()
    await asyncio.sleep(10)

    await drone.action.disarm()


    print("-- Stopping offboard")
    try:
        await drone.offboard.stop()
    except OffboardError as error:
        print(
            f"Stopping offboard mode failed with error code: {error._result.result}")


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())

```

is there any possible reason for it and a way around it?

**Comment by julianoes** [comment]
Please share a logfile uploaded to http://logs.px4.io and maybe share the output that you see, e.g. statustext, or the full debugging output like you see it when you start mavsdk_server separately:

http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/#debug-connection-issues

**Comment by rishireddi** [comment]
> so I'm trying to use the offboard_position_ned to control the final landing of my drone to the desired position (manual control doesn't seem to work) the example here [https://github.com/mavlink/MAVSDK-Python/blob/main/examples/offboard_position_ned.py](here) seems to work, but when I begin it off by taking off to an altitude and setting that altitude to `offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))` the code doesn't work and it just lands after take off.
> 
> so for example
> 
> ```
> #!/usr/bin/env python3
> 
> import asyncio
> 
> from mavsdk import System
> from mavsdk.offboard import (OffboardError, PositionNedYaw)
> 
> 
> async def run():
>     
>     drone = System()
>     await drone.connect(system_address="serial:///dev/ttyACM0:115200")
> 
>     print("Waiting for drone to connect...")
>     async for state in drone.core.connection_state():
>         if state.is_connected:
>             print(f"-- Connected to drone!")
>             break
> 
>     print("Waiting for drone to have a global position estimate...")
>     async for health in drone.telemetry.health():
>         if health.is_global_position_ok and health.is_home_position_ok:
>             print("-- Global position estimate OK")
>             break
> 
>     print("-- Arming")
>     await drone.action.arm()
> 
>     print("-- Setting initial setpoint")
>     await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))
> 
>     print("-- Starting offboard")
>     try:
>         await drone.offboard.start()
>     except OffboardError as error:
>         print(
>             f"Starting offboard mode failed with error code: {error._result.result}")
>         print("-- Disarming")
>         await drone.action.disarm()
>         return
> 
>     print("-- Go 0m North, 0m East, -5m Down within local coordinate system")
>     await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, -5.0, 0.0))
>     await asyncio.sleep(10)
> 
>     print("-- Go 5m North, 0m East, -5m Down within local coordinate system, turn to face East")
>     await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))
>     await asyncio.sleep(10)
> 
>     await drone.action.land()
>     await asyncio.sleep(10)
> 
>     await drone.action.disarm()
> 
> 
>     print("-- Stopping offboard")
>     try:
>         await drone.offboard.stop()
>     except OffboardError as error:
>         print(
>             f"Stopping offboard mode failed with error code: {error._result.result}")
> 
> 
> if __name__ == "__main__":
>     loop = asyncio.get_event_loop()
>     loop.run_until_complete(run())
> ```
> 
> this example works well, but when i try a takeoff before beginning the offboard mode the drone just lands after takeoff. example like in this code
> 
> ```
> #!/usr/bin/env python3
> 
> """
> Caveat when attempting to run the examples in non-gps environments:
> `drone.offboard.stop()` will return a `COMMAND_DENIED` result because it
> requires a mode switch to HOLD, something that is currently not supported in a
> non-gps environment.
> """
> 
> import asyncio
> 
> from mavsdk import System
> from mavsdk.offboard import (OffboardError, PositionNedYaw)
> 
> 
> async def run():
>     """ Does Offboard control using position NED coordinates. """
> 
>     drone = System()
>     await drone.connect(system_address="serial:///dev/ttyACM0:115200")
> 
>     print("Waiting for drone to connect...")
>     async for state in drone.core.connection_state():
>         if state.is_connected:
>             print(f"-- Connected to drone!")
>             break
> 
>     print("Waiting for drone to have a global position estimate...")
>     async for health in drone.telemetry.health():
>         if health.is_global_position_ok and health.is_home_position_ok:
>             print("-- Global position estimate OK")
>             break
> 
>     print("-- Arming")
>     await drone.action.arm()
> 
>     print("-- Taking off")
>     await drone.action.set_takeoff_altitude(20)
>     await drone.action.takeoff()
>     await asyncio.sleep(15)
> 
>     print("-- Setting initial setpoint")
>     await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))
> 
>     print("-- Starting offboard")
>     try:
>         await drone.offboard.start()
>     except OffboardError as error:
>         print(
>             f"Starting offboard mode failed with error code: {error._result.result}")
>         print("-- Disarming")
>         await drone.action.disarm()
>         return
> 
>     print("-- Go 0m North, 0m East, -5m Down within local coordinate system")
>     await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, -5.0, 0.0))
>     await asyncio.sleep(10)
> 
>     print("-- Go 5m North, 0m East, -5m Down within local coordinate system, turn to face East")
>     await drone.offboard.set_position_ned(PositionNedYaw(0.0, 0.0, 0.0, 0.0))
>     await asyncio.sleep(10)
> 
>     await drone.action.land()
>     await asyncio.sleep(10)
> 
>     await drone.action.disarm()
> 
> 
>     print("-- Stopping offboard")
>     try:
>         await drone.offboard.stop()
>     except OffboardError as error:
>         print(
>             f"Stopping offboard mode failed with error code: {error._result.result}")
> 
> 
> if __name__ == "__main__":
>     loop = asyncio.get_event_loop()
>     loop.run_until_complete(run())
> ```
> 
> is there any possible reason for it and a way around it?

Hi, I've got the same issue. Could you please share the resolving steps if you have found a way to resolve this.
Thank you in advance.

**Comment by julianoes** [comment]
I got notified about this but I don't see any change or comment. In any case there was no follow up by the OP so I'm closing this.
