### ISSUE TITLE
Python 3.10 compatibility issues

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK-Python#507]
I tried the examples with Python 3.10 and I get a warning:
```
DeprecationWarning: There is no current event loop
```

And also, everything just stalls and I have to kill it.

**Comment by AlexKlimaj** [comment]
I am seeing this as well. If I try to run mavsdk python too soon after rebooting the FC.

**Comment by AlexKlimaj** [comment]
It looks like you already fixed this https://github.com/mavlink/MAVSDK-Python/pull/542

**Comment by julianoes** [comment]
Ok, so I'll close that then, thanks @AlexKlimaj.
