### ISSUE TITLE
Problem with starting jmavsim

### ISSUE THREAD

**Issue by scps990210** [mavlink/MAVSDK-Python#512]
I have Installed WSL2 by this [page](https://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html#windows-10-gui-support) and it seems no problem to step7 make px4_sitl.But when i type "make px4_sitl jmavsim" to start jmavsim it encounter some problems below
![image](https://user-images.githubusercontent.com/66359433/189109320-c34dc6d8-98c4-4ee6-aeee-a4320936b979.png)
How can i solve it ? or is there anything I'm doing wrong?

**Comment by JonasVautherin** [comment]
jmavsim is independent from MAVSDK. I would suggest you ask that question in the PX4 community :+1:

**Comment by julianoes** [comment]
What @JonasVautherin said, and check the troubleshooting docs:
https://docs.px4.io/main/en/simulation/jmavsim.html#troubleshooting
