### ISSUE TITLE
How to adjust landing or takeoff speed?

### ISSUE THREAD

**Issue by jaekyoungkwon** [mavlink/MAVSDK-Python#517]
Hello
I'm trying to set landing speed.
I upload 6 mission items and checked the flight mode changed to landing state after all the missions.
But it seems so slowly when it's landing.(I could see only 1m/s)

I want to change landing speed but I have no idea how to change the landing speed.
Which code do I have to put in this code?

    if await drone.mission.is_mission_finished():

        print("-- Landing")
        await drone.action.land()
        await termination_task
        print("-- Landed")

**Comment by JonasVautherin** [comment]
Isn't that a PX4 param?

**Comment by julianoes** [comment]
If it's a PX4 param, then you can set that param using QGroundControl, or as part of your script using the param plugin.

**Comment by jaekyoungkwon** [comment]
![image](https://user-images.githubusercontent.com/46947184/192661587-c646e8f6-afb8-4a6f-ad00-e0c16d5c66e0.png)

I've added this code the above codes:
    await drone.param.set_param_float("MPC_Z_VEL_MAX_DN", 4.0)

But still I can see the velocity of down is 1.0m/s

**Comment by jaekyoungkwon** [comment]
Oh I found the answer!
The Parameter what I have to change is 'MPC_Z_V_AUTO_DN'
I changed code like:

    await drone.param.set_param_float("MPC_Z_V_AUTO_DN", 4.0)

and I checked the landing speed is 4m/s
Thank you!
