### ISSUE TITLE
How to use telemetry.actuator_output_status ?

### ISSUE THREAD

**Issue by YasinBedirhanSimsek** [mavlink/MAVSDK-Python#523]
I am trying to implement a single axis very simple gimbal with a servo motor. 

Servo motor is connected to the aux1 pin of the Orange Cube with PX4

I can control the servo with `system.action.set_actuator()` but I need to know the current value of the aux1 pwm output.

That way I will know the angle of the servo head. 

`async for i in system.telemetry.actuator_output_status():` blocks the whole execution and nothing happens, no data is updated

**Comment by julianoes** [comment]
That's all not really set up for that. I suggest to use the gimbal API of MAVSDK and set up PX4 to use gimbal v2 as the input and PWM as the output. You can select the gimbal output pin in the actuator configuration in QGC when you use latest PX4 developer (main branch).

The docs have been updated here but the changes don't seem to be pushed yet: https://github.com/PX4/PX4-user_guide/pull/2085/files
