### ISSUE TITLE
Invalid argument error with mission_items in mission_raw.py

### ISSUE THREAD

**Issue by Moseskota** [mavlink/MAVSDK-Python#550]
Hi @julianoes 

I have been trying to execute a simple mission with mission_items using mission_raw.py.  I referred to the existing github issues related to this particular issue, I still get invalid argument error...
I am trying to execute a simple mission with RTL. I am doubtful whether to give the lat,long, alt as zeros ( i gave the home location) for RTL [MAV_CMD (20)] as other parameters(1-4) are zeros (according to mavlink_mission.cpp) 

Here is the code..suggest corrections needed:
```
import asyncio
from mavsdk import System
from mavsdk.mission_raw import MissionItem




async def run():
    drone = System()
    await drone.connect(system_address="udp://:14540")

    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"-- Connected to drone!")
            break

    print_mission_progress_task = asyncio.ensure_future(
        print_mission_progress(drone))
    
    # included to add redundancy 
    running_tasks = [print_mission_progress_task]
    termination_task = asyncio.ensure_future(observe_is_in_air(drone, running_tasks))

    mission_items = []
    mission_items.append(MissionItem(1,6, 22, 1, 1, 0, 10,  0, float('nan'),  169385325,  817945425, 10.0, 0))
    mission_items.append(MissionItem(2,6, 16, 1, 1, 0, 10,  0, float('nan'),  169388925,  817942725, 10.0, 0))
    mission_items.append(MissionItem(3,2, 20, 1, 0, 0,  0,  0,   0,           169385025,  817940325, 10.0, 0))

 
      
    
    await drone.mission_raw.upload_mission(mission_items)

    print("mission uploaded")
    await asyncio.sleep(2)

    print("Waiting for drone to have a global position estimate...")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok and health.is_home_position_ok:
            print("-- Global position estimate OK")
            break
    
    await drone.action.arm()
    print("arming the done")

    await drone.mission_raw.start_mission()
    print("started the mission")
    
    await termination_task


async def print_mission_progress(drone):
    async for mission_progress in drone.mission.mission_progress():
        print(f"Mission progress: "
              f"{mission_progress.current}/"
              f"{mission_progress.total}")
   
       
   

async def observe_is_in_air(drone, running_tasks):
    was_in_air = False

    async for is_in_air in drone.telemetry.in_air():
        if is_in_air:
            was_in_air = is_in_air

    if was_in_air and not is_in_air:
        for task in running_tasks:
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass
        await asyncio.get_event_loop().shutdown_asyncgens()

        return


if __name__ == "__main__":
    # Run the asyncio loop
    asyncio.run(run())
```
error:
```
 raise MissionRawError(result, "upload_mission()", mission_items)
mavsdk.mission_raw.MissionRawError: INVALID_ARGUMENT: 'Invalid Argument'; origin: upload_mission(); params: ([<mavsdk.mission_raw.MissionItem object at 0x7f89ac7830a0>, <mavsdk.mission_raw.MissionItem object at 0x7f89ac7836a0>, <mavsdk.mission_raw.MissionItem object at 0x7f89ac7837f0>],)
```

PS: similar arguments with just takeoff and land MAV_CMDs also result in the same error.

**Comment by julianoes** [comment]
Ok, the `seq` and `current` fields were wrong, here is what uploads for me:

```
#!/usr/bin/env python

import asyncio
from mavsdk import System
from mavsdk.mission_raw import MissionItem




async def run():
    drone = System(mavsdk_server_address="localhost")
    await drone.connect()

    print("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            print(f"-- Connected to drone!")
            break

    print_mission_progress_task = asyncio.ensure_future(
        print_mission_progress(drone))

    # included to add redundancy
    running_tasks = [print_mission_progress_task]
    termination_task = asyncio.ensure_future(observe_is_in_air(drone, running_tasks))

    mission_items = []
    mission_items.append(MissionItem(0,6, 22, 1, 1, 0, 10,  0, float('nan'),  169385325,  817945425, 10.0, 0))
    mission_items.append(MissionItem(1,6, 16, 0, 1, 0, 10,  0, float('nan'),  169388925,  817942725, 10.0, 0))
    mission_items.append(MissionItem(2,2, 20, 0, 0, 0,  0,  0,   0,           169385025,  817940325, 10.0, 0))




    await drone.mission_raw.upload_mission(mission_items)

    print("mission uploaded")
    await asyncio.sleep(2)

    print("Waiting for drone to have a global position estimate...")
    async for health in drone.telemetry.health():
        if health.is_global_position_ok and health.is_home_position_ok:
            print("-- Global position estimate OK")
            break

    await drone.action.arm()
    print("arming the done")

    await drone.mission_raw.start_mission()
    print("started the mission")

    await termination_task


async def print_mission_progress(drone):
    async for mission_progress in drone.mission.mission_progress():
        print(f"Mission progress: "
              f"{mission_progress.current}/"
              f"{mission_progress.total}")




async def observe_is_in_air(drone, running_tasks):
    was_in_air = False

    async for is_in_air in drone.telemetry.in_air():
        if is_in_air:
            was_in_air = is_in_air

    if was_in_air and not is_in_air:
        for task in running_tasks:
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass
        await asyncio.get_event_loop().shutdown_asyncgens()

        return


if __name__ == "__main__":
    # Run the asyncio loop
    asyncio.run(run())

```

**Comment by Moseskota** [comment]
> Ok, the `seq` and `current` fields were wrong, here is what uploads for me:
> 
> ```
> #!/usr/bin/env python
> 
> import asyncio
> from mavsdk import System
> from mavsdk.mission_raw import MissionItem
> 
> 
> 
> 
> async def run():
>     drone = System(mavsdk_server_address="localhost")
>     await drone.connect()
> 
>     print("Waiting for drone to connect...")
>     async for state in drone.core.connection_state():
>         if state.is_connected:
>             print(f"-- Connected to drone!")
>             break
> 
>     print_mission_progress_task = asyncio.ensure_future(
>         print_mission_progress(drone))
> 
>     # included to add redundancy
>     running_tasks = [print_mission_progress_task]
>     termination_task = asyncio.ensure_future(observe_is_in_air(drone, running_tasks))
> 
>     mission_items = []
>     mission_items.append(MissionItem(0,6, 22, 1, 1, 0, 10,  0, float('nan'),  169385325,  817945425, 10.0, 0))
>     mission_items.append(MissionItem(1,6, 16, 0, 1, 0, 10,  0, float('nan'),  169388925,  817942725, 10.0, 0))
>     mission_items.append(MissionItem(2,2, 20, 0, 0, 0,  0,  0,   0,           169385025,  817940325, 10.0, 0))
> 
> 
> 
> 
>     await drone.mission_raw.upload_mission(mission_items)
> 
>     print("mission uploaded")
>     await asyncio.sleep(2)
> 
>     print("Waiting for drone to have a global position estimate...")
>     async for health in drone.telemetry.health():
>         if health.is_global_position_ok and health.is_home_position_ok:
>             print("-- Global position estimate OK")
>             break
> 
>     await drone.action.arm()
>     print("arming the done")
> 
>     await drone.mission_raw.start_mission()
>     print("started the mission")
> 
>     await termination_task
> 
> 
> async def print_mission_progress(drone):
>     async for mission_progress in drone.mission.mission_progress():
>         print(f"Mission progress: "
>               f"{mission_progress.current}/"
>               f"{mission_progress.total}")
> 
> 
> 
> 
> async def observe_is_in_air(drone, running_tasks):
>     was_in_air = False
> 
>     async for is_in_air in drone.telemetry.in_air():
>         if is_in_air:
>             was_in_air = is_in_air
> 
>     if was_in_air and not is_in_air:
>         for task in running_tasks:
>             task.cancel()
>             try:
>                 await task
>             except asyncio.CancelledError:
>                 pass
>         await asyncio.get_event_loop().shutdown_asyncgens()
> 
>         return
> 
> 
> if __name__ == "__main__":
>     # Run the asyncio loop
>     asyncio.run(run())
> ```



> Ok, the `seq` and `current` fields were wrong, here is what uploads for me:
> 
> ```
> #!/usr/bin/env python
> 
> import asyncio
> from mavsdk import System
> from mavsdk.mission_raw import MissionItem
> 
> 
> 
> 
> async def run():
>     drone = System(mavsdk_server_address="localhost")
>     await drone.connect()
> 
>     print("Waiting for drone to connect...")
>     async for state in drone.core.connection_state():
>         if state.is_connected:
>             print(f"-- Connected to drone!")
>             break
> 
>     print_mission_progress_task = asyncio.ensure_future(
>         print_mission_progress(drone))
> 
>     # included to add redundancy
>     running_tasks = [print_mission_progress_task]
>     termination_task = asyncio.ensure_future(observe_is_in_air(drone, running_tasks))
> 
>     mission_items = []
>     mission_items.append(MissionItem(0,6, 22, 1, 1, 0, 10,  0, float('nan'),  169385325,  817945425, 10.0, 0))
>     mission_items.append(MissionItem(1,6, 16, 0, 1, 0, 10,  0, float('nan'),  169388925,  817942725, 10.0, 0))
>     mission_items.append(MissionItem(2,2, 20, 0, 0, 0,  0,  0,   0,           169385025,  817940325, 10.0, 0))
> 
> 
> 
> 
>     await drone.mission_raw.upload_mission(mission_items)
> 
>     print("mission uploaded")
>     await asyncio.sleep(2)
> 
>     print("Waiting for drone to have a global position estimate...")
>     async for health in drone.telemetry.health():
>         if health.is_global_position_ok and health.is_home_position_ok:
>             print("-- Global position estimate OK")
>             break
> 
>     await drone.action.arm()
>     print("arming the done")
> 
>     await drone.mission_raw.start_mission()
>     print("started the mission")
> 
>     await termination_task
> 
> 
> async def print_mission_progress(drone):
>     async for mission_progress in drone.mission.mission_progress():
>         print(f"Mission progress: "
>               f"{mission_progress.current}/"
>               f"{mission_progress.total}")
> 
> 
> 
> 
> async def observe_is_in_air(drone, running_tasks):
>     was_in_air = False
> 
>     async for is_in_air in drone.telemetry.in_air():
>         if is_in_air:
>             was_in_air = is_in_air
> 
>     if was_in_air and not is_in_air:
>         for task in running_tasks:
>             task.cancel()
>             try:
>                 await task
>             except asyncio.CancelledError:
>                 pass
>         await asyncio.get_event_loop().shutdown_asyncgens()
> 
>         return
> 
> 
> if __name__ == "__main__":
>     # Run the asyncio loop
>     asyncio.run(run())
> ```

Thank you very much for the prompt reply. But i have a question. For ardupilot , i saw that the seq starts with 0 whereas for px4 it starts with 1.

**Comment by Moseskota** [comment]
@julianoes 
Thank you very much for your prompt reply.
