### ISSUE TITLE
How is a prop failure detected ?

### ISSUE THREAD

**Issue by m-sienk** [mavlink/MAVSDK-Python#553]
How is a prop/ ESC failure detected in mavsdk-python?

Take a scenario in which I have an aircraft that can sustain a single prop failure and stay in the air. However, I need to detect that failure and trigger an emergency landing using computer vision and custom landing logic.

For example I can inject a GPS failure:
`await aircraft.system.failure.inject(FailureUnit.SENSOR_GPS, FailureType.OFF, instance=0)`

And here I could detect if the gps_info value suddenly jumped to NO_GPS and num_satellites to 255.
```
async def gps_info(drone):
    async for gps_info in drone.telemetry.gps_info():
        if gps_info.fix_type is NO_GPS and gps_info.num_satellites == 255:
            print("GPS failure")
```
	
Do I have the right idea as to how to detect a failure as outlined above and will a prop failure be implemented in roughly the same way - that is an async for and a status value ?

**Comment by julianoes** [comment]
Not all failures are supported on the autopilot side. MAVSDK is just the messenger and tries to send these failures to the autopilot.
