### ISSUE TITLE
pause_mission vs hold

### ISSUE THREAD

**Issue by m-sienk** [mavlink/MAVSDK-Python#584]
Documentation for mavsdk.mission.pause_mission()  states: 
Pausing the mission puts the vehicle into HOLD mode. A multicopter should just hover at the spot while a fixedwing vehicle should loiter around the location where it paused.

What exactly is the difference between  mavsdk.mission.pause_mission() and mavsdk.action.hold(), why would you use one opposed to the other?

**Comment by JonasVautherin** [comment]
It is [exactly](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/action/action_impl.cpp#L511) [the same](https://github.com/mavlink/MAVSDK/blob/main/src/mavsdk/plugins/mission/mission_impl.cpp#L905) :innocent:
