### ISSUE TITLE
How to change the velocity of the drone while using offboard set_position_velocity_ned 

### ISSUE THREAD

**Issue by Bharannn** [mavlink/MAVSDK-Python#594]
Hi,
I've used PositionNedYaw before, now i want to restrict my drone's velocity to 1m/s throughout my mission, so I'm trying to use "set_position_velocity_ned" but couldn't figure out how it works. I'm attaching a snippet below, please let me now what changes i need to do or suggest any other ways i can restrict the velocity of the drone while using offboard.

    await drone.offboard.set_position_velocity_ned(PositionNedYaw(5.0, 5.0, -1.0, 90.0), VelocityNedYaw(1.0, 1.0, -1.0, 0.0))
    await asyncio.sleep(5)

**Comment by julianoes** [comment]
The velocity that you add is the feed-forward, not the limit!

Instead I would try the params. Try [MPC_XY_CRUISE](https://docs.px4.io/v1.13/en/advanced_config/parameter_reference.html#MPC_XY_CRUISE) and/or [MPC_XY_VEL_MAX](https://docs.px4.io/v1.13/en/advanced_config/parameter_reference.html#MPC_XY_VEL_MAX).
