### ISSUE TITLE
trying to run quick start for MAVSDK-Python (OSError: [Errno 8] Exec format error: '/home/wcjai/MAVSDK-Python/mavsdk/bin/mavsdk_server')

### ISSUE THREAD

**Issue by WCjai** [mavlink/MAVSDK-Python#608]
hello i installed the MAVSDK-python as per installation guide, after that i try to do quick start from the MAVSDK guide website (https://mavsdk.mavlink.io/main/en/python/quickstart.html), when i ran "await drone.connect()" it shows error, i tried to search other post simular, but couldn't find solution 

![error_3](https://github.com/mavlink/MAVSDK-Python/assets/67961391/6ef1136e-15e6-4c7b-a001-3bcd69806df3)

**Comment by JonasVautherin** [comment]
How did you install? With `pip`? Which version is that?

Also what kind of computer is it? I mean the CPU architecture?

**Comment by WCjai** [comment]
tried both way of installing, using pip and also build from source, iam using a laptop running ubuntu 20.04 , CPU Architecture:                    x86_64

**Comment by arpitpara** [comment]
are you using mavsdk and mavsdk-python together?
Try making a virtual environment and then install evrything fresh related to mavsdk-python.

**Comment by JonasVautherin** [comment]
Can you try to download and run `mavsdk_server_musl_x86_64` from https://github.com/mavlink/MAVSDK/releases/tag/v1.4.16? What does it say?

**Comment by arpitpara** [comment]
I checked it. And it works fine.
![Screenshot from 2023-07-27 01-08-48](https://github.com/mavlink/MAVSDK-Python/assets/58958058/137a6b71-62c1-4815-a49f-d3914f626c52)
![Screenshot from 2023-07-27 01-08-55](https://github.com/mavlink/MAVSDK-Python/assets/58958058/3ab3bcd7-f50c-4150-9bcf-255ce5a9a25f)
![Screenshot from 2023-07-27 01-09-12](https://github.com/mavlink/MAVSDK-Python/assets/58958058/73bbc0de-40b7-4ad3-9646-47b2617223be)

**Comment by JonasVautherin** [comment]
@arpitpara: do you also have the error when using `pip`? i.e. `OSError: [Errno 8] Exec format error: '/home/wcjai/MAVSDK-Python/mavsdk/bin/mavsdk_server'`?

**Comment by arpitpara** [comment]
No.Everything seems to work fine.

**Comment by JonasVautherin** [comment]
Right :rofl:. Well then I was asking @WCjai to try the musl executable :grin:

**Comment by arpitpara** [comment]
> Right rofl. Well then I was asking @WCjai to try the musl executable 😁

Better you quote right person next time. I was also in little dilema till now.

**Comment by WCjai** [comment]
Sorry guys, I am currently out of town but will try the solutions and provide the information here

**Comment by WCjai** [comment]
> Can you try to download and run `mavsdk_server_musl_x86_64` from https://github.com/mavlink/MAVSDK/releases/tag/v1.4.16? What does it say?

thank you all, the server works fine after creating new python environment the program is now connecting to the drone
