### ISSUE TITLE
In mission mode is it possible to ajust the drone position to the left/right, accelarate/decelerate?

### ISSUE THREAD

**Issue by l0ad-pri0r** [mavlink/MAVSDK-Python#614]
Hi, I'm trying to make a drone (in SITL for now) follow a predetermined route of waypoints (mission mode) behind a subject.
I need to keep the camera (fixed one, not with a gimbal) centered on that subject. 
Some options came to mind on how to do it. Either messing with the yaw and velocity or with the position.
Follow-me mode can be an option, but the last resort. Preferably, the drone should be in mission mode.
Can it be done? How?

Thanks in advance 🙏

**Comment by julianoes** [comment]
It's either or: either mission mode with waypoints or custom control using something like offboard or follow me.
