### ISSUE TITLE
examples/manual_control.py file  does not run

### ISSUE THREAD

**Issue by alanmehio** [mavlink/MAVSDK-Python#618]
The line needs to be change 
from 
asyncio.run(run())
to 
asyncio.run(manual_controls())

Also, there is a error once this file get executed under the SITL ( jmavsim simulation ) as below

**mavsdk.action.ActionError: COMMAND_DENIED: 'Command Denied'; origin: arm(); params: ()**

Steps to reproduce:
1- run the jmavsim simulation  from command line as below
make px4_sitl_default jmavsim
2- from IDE  run  manual_control.py

**Comment by JonasVautherin** [comment]
Would you like to open a pull request? :blush:

**Comment by alanmehio** [comment]
Yes, I will do that.
Cheers
Alan

**Comment by alanmehio** [comment]
This issue is closed now since the pull request is created.

**Comment by JonasVautherin** [comment]
Nitpick: the way it works usually is that we close the issue after the PR is merged ("the PR closes the issue").

**Comment by alanmehio** [comment]
This has been noted
Cheers
Alan
