### ISSUE TITLE
Cannot Upgrade Firmware on MacOS

### ISSUE THREAD

**Issue by ilysec** [mavlink/MAVSDK-Python#655]
When I plug in my PX4 via a direct USB-C cable, i cannot upgrade the firmware on MacOS Sonoma 14.2.1.

<img width="1071" alt="image" src="https://github.com/mavlink/MAVSDK-Python/assets/82593453/267fafae-2624-4a48-ac8d-77f28c2f2e18">

**Comment by julianoes** [comment]
That's a PX4 or QGC issue, not MAVSDK.
