### ISSUE TITLE
Analyzing log files or Distance travelled data from mavsdk python

### ISSUE THREAD

**Issue by arpitpara** [mavlink/MAVSDK-Python#708]
Hi
I've been wondering if we can calculate distance traveled by the vehicle in real-time and plot it live.
Also, if we can analyze the logs of flight through the same.

**Comment by julianoes** [comment]
You will have to subsribe to position updates and do the integration yourself.

**Comment by arpitpara** [comment]
I am working on GPS-Denied environments. So I can't calculate it with GPS. I working with VIO .

**Comment by julianoes** [comment]
Use the local position updates: http://mavsdk-python-docs.s3-website.eu-central-1.amazonaws.com/plugins/telemetry.html#mavsdk.telemetry.PositionVelocityNed

**Comment by arpitpara** [comment]
How is odometry is different from PositionVeocityNed

**Comment by julianoes** [comment]
Odometry would be the info from an odometry system. Position velocity come from the autopilot's estimator.
