### ISSUE TITLE
Takeoff altitude fixed to 2 [m]?

### ISSUE THREAD

**Issue by kripper** [mavlink/MAVSDK-Python#743]
We do:

```
await drone.action.set_takeoff_altitude(1)
await self.vehicle.system.action.takeoff()
```

But the drone is receiving a Mavlink message with param alt = 2 [m]

**Comment by kripper** [comment]
This is the received mavlink msg:

![image](https://github.com/user-attachments/assets/cb80cc4d-f71b-422d-b873-f2683d235acf)

**Comment by julianoes** [comment]
Can you add that to https://github.com/mavlink/MAVSDK-Python/issues/743. Closing as duplicate.

**Comment by kripper** [comment]
> Can you add that to #743

This here is 743 :-)
You probably mean another issue.

**Comment by kripper** [comment]
Oops. Sorry. No idea how it got posted twice.

You meant https://github.com/mavlink/MAVSDK-Python/issues/742#issuecomment-2526729351
