### ISSUE TITLE
Generate reference docs for Python frontend

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK-Python#82]
@JonasVautherin we should generate reference docs for the Python bindings.

**Comment by JonasVautherin** [comment]
Agreed. The idea is to generate docs (doxygen-like) from the proto files. I am quite sure it is possible, and I had seen somebody doing that specifically for C#. I'd like to do something similar, but for all our bindings at once.

If somebody wants to look into how to extend our protoc plugin to do that, I'm happy to have a discussion :blush:.

**Comment by hamishwillee** [comment]
I'd love to work on this. Just time poor. Python docs  are petty standardised, and most use Sphinx to auto extract comments.

**Comment by JonasVautherin** [comment]
Note that we should first get the comments there :sweat_smile:. That's the issue [here](https://github.com/mavlink/MAVSDK-Proto/issues/91).

**Comment by julianoes** [comment]
Awesome, we should also publish them somehow on s3 and link to them.
